#pragma once

#include "VisualStyleParts.h"

#define AL(arr) (sizeof(arr) / sizeof(arr[0]))
#define VS_STATE(state) state, AL(state)
#define VS_STATE_DEFAULT VS_STATE(STATES_COMMON_DEFAULT)

namespace libmsstyle
{
	const PartMap PARTS_ADDRESSBAND[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE(STATES_EDITTEXT_BG) }, // reuse states
	};

	const PartMap PARTS_BARRIERPAGE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PANEBACKGROUND", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_BREADCRUMBBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "OVERFLOWCHEVRON", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_BUTTON[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PUSHBUTTON", VS_STATE(STATES_PUSHBUTTON) },
		{ 2, "RADIOBUTTON", VS_STATE(STATES_RADIOBUTTON) },
		{ 3, "CHECKBOX", VS_STATE(STATES_CHECKBOX) },
		{ 4, "GROUPBOX", VS_STATE(STATES_GROUPBOX) },
		{ 5, "USERBUTTON", VS_STATE_DEFAULT },
		{ 6, "COMMANDLINK", VS_STATE(STATES_COMMANDLINK) },
		{ 7, "COMMANDLINKGLYPH", VS_STATE(STATES_COMMANDLINKGLYPHS) },
		{ 8, "RADIOBUTTON_LITE", VS_STATE(STATES_RADIOBUTTON) },
		{ 9, "CHECKBOX_LITE", VS_STATE(STATES_CHECKBOX) },
		{ 10, "GROUPBOX_LITE", VS_STATE(STATES_GROUPBOX) },
	};

	const PartMap PARTS_CLOCK[] =
	{
		{ 0, "Common Properties", VS_STATE(STATES_PUSHBUTTON) },
		{ 1, "TIME", VS_STATE(STATES_PUSHBUTTON) },
	};

	const PartMap PARTS_CHARTVIEW[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "CPU_BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "CPU_BORDER", VS_STATE_DEFAULT },
		{ 3, "CPU_GRID", VS_STATE_DEFAULT },
		{ 4, "CPU_LINE1", VS_STATE_DEFAULT },
		{ 5, "CPU_LINE1FILL", VS_STATE_DEFAULT },
		{ 6, "CPU_LINE2", VS_STATE_DEFAULT },
		{ 7, "CPU_LINE2FILL", VS_STATE_DEFAULT },
		{ 8, "MEMORY_BACKGROUND", VS_STATE_DEFAULT },
		{ 9, "MEMORY_BORDER", VS_STATE_DEFAULT },
		{ 10, "MEMORY_GRID", VS_STATE_DEFAULT },
		{ 11, "MEMORY_LINE1", VS_STATE_DEFAULT },
		{ 12, "MEMORY_LINE1FILL", VS_STATE_DEFAULT },
		{ 13, "MEMORY_LINE2", VS_STATE_DEFAULT },
		{ 14, "MEMORY_LINE2FILL", VS_STATE_DEFAULT },
		{ 15, "DISK_BACKGROUND", VS_STATE_DEFAULT },
		{ 16, "DISK_BORDER", VS_STATE_DEFAULT },
		{ 17, "DISK_GRID", VS_STATE_DEFAULT },
		{ 18, "DISK_LINE1", VS_STATE_DEFAULT },
		{ 19, "DISK_LINE1FILL", VS_STATE_DEFAULT },
		{ 20, "DISK_LINE2", VS_STATE_DEFAULT },
		{ 21, "DISK_LINE2FILL", VS_STATE_DEFAULT },
		{ 22, "NETWORK_BACKGROUND", VS_STATE_DEFAULT },
		{ 23, "NETWORK_BORDER", VS_STATE_DEFAULT },
		{ 24, "NETWORK_GRID", VS_STATE_DEFAULT },
		{ 25, "NETWORK_LINE1", VS_STATE_DEFAULT },
		{ 26, "NETWORK_LINE1FILL", VS_STATE_DEFAULT },
		{ 27, "NETWORK_LINE2", VS_STATE_DEFAULT },
		{ 28, "NETWORK_LINE2FILL", VS_STATE_DEFAULT },
		{ 29, "COPY_BORDER", VS_STATE(STATES_CHARTVIEW_LINE) },
		{ 30, "COPY_GRID", VS_STATE(STATES_CHARTVIEW_LINE) },
		{ 31, "COPY_LINE1", VS_STATE(STATES_CHARTVIEW_LINE) },
		{ 32, "COPY_LINE1FILL", VS_STATE(STATES_CHARTVIEW_LINE) },
		{ 33, "COPY_LINE2", VS_STATE(STATES_CHARTVIEW_LINE) },
		{ 34, "COPY_LINE2FILL", VS_STATE(STATES_CHARTVIEW_LINE) },
		{ 35, "CPU_SCALELINE", VS_STATE_DEFAULT },
		{ 36, "CPU_SCALELINETEXT", VS_STATE_DEFAULT },
		{ 37, "MEMORY_SCALELINE", VS_STATE_DEFAULT },
		{ 38, "MEMORY_SCALELINETEXT", VS_STATE_DEFAULT },
		{ 39, "DISK_SCALELINE", VS_STATE_DEFAULT },
		{ 40, "DISK_SCALELINETEXT", VS_STATE_DEFAULT },
		{ 41, "NETWORK_SCALELINE", VS_STATE_DEFAULT },
		{ 42, "NETWORK_SCALELINETEXT", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_COMMANDMODULE_WIN7[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "MODULEBACKGROUND", VS_STATE_DEFAULT },
		{ 2, "MODULEBACKGROUNDCOLORS", VS_STATE_DEFAULT },
		{ 3, "TASKBUTTON", VS_STATE(STATES_COMMANDMODULE_SPLITBUTTON) },
		{ 4, "SPLITBUTTONLEFT", VS_STATE(STATES_COMMANDMODULE_SPLITBUTTON) },
		{ 5, "SPLITBUTTONRIGHT", VS_STATE(STATES_COMMANDMODULE_SPLITBUTTON) },
		{ 6, "MENUGLYPH", VS_STATE_DEFAULT },
		{ 7, "OVERFLOWGLYPH", VS_STATE_DEFAULT },
		{ 8, "LIBRARYPANEMENUGLYPH", VS_STATE(STATES_COMMANDMODULE_LIBRARYPANE_GEN) },
		{ 9, "LIBRARYPANETOPVIEW", VS_STATE(STATES_COMMANDMODULE_LIBRARYPANE_GEN) },
		{ 10, "LIBRARYPANEIDENTIFIER", VS_STATE_DEFAULT },
		{ 11, "LIBRARYPANEBACKGROUND", VS_STATE_DEFAULT },
		{ 12, "LIBRARYPANEOVERLAY", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_COMMANDMODULE_WIN8[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "MODULEBACKGROUND", VS_STATE_DEFAULT },
		{ 2, "MODULEBACKGROUNDCOLORS", VS_STATE_DEFAULT },
		{ 3, "TASKBUTTON", VS_STATE(STATES_COMMANDMODULE_SPLITBUTTON) },
		{ 4, "SPLITBUTTONLEFT", VS_STATE(STATES_COMMANDMODULE_SPLITBUTTON) },
		{ 5, "SPLITBUTTONRIGHT", VS_STATE(STATES_COMMANDMODULE_SPLITBUTTON) },
		{ 6, "MENUGLYPH", VS_STATE_DEFAULT },
		{ 7, "OVERFLOWGLYPH", VS_STATE_DEFAULT },
		{ 8, "LIBRARYPANEMENUGLYPH", VS_STATE(STATES_COMMANDMODULE_LIBRARYPANE_GEN) },
		{ 9, "LIBRARYPANETOPVIEW", VS_STATE(STATES_COMMANDMODULE_LIBRARYPANE_GEN) },
		{ 10, "LIBRARYPANEBACKGROUND", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_COMMUNICATIONS[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TAB", VS_STATE(STATES_TAB) },
	};

	const PartMap PARTS_COMBOBOX[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "DROPDOWNBUTTON", VS_STATE_DEFAULT },
		{ 2, "BACKGROUND", VS_STATE_DEFAULT },
		{ 3, "TRANSPARENTBACKGROUND", VS_STATE(STATES_CB_TRANSPARENTBG) },
		{ 4, "BORDER", VS_STATE(STATES_CB_BORDER) },
		{ 5, "READONLY", VS_STATE(STATES_CB_READONLY) },
		{ 6, "DROPDOWNBUTTONRIGHT", VS_STATE(STATES_CB_DROPDOWNLR) },
		{ 7, "DROPDOWNBUTTONLEFT", VS_STATE(STATES_CB_DROPDOWNLR) },
		{ 8, "CUEBANNER", VS_STATE(STATES_CB_CUEBANNER) },
	};

	const PartMap PARTS_CONTROLPANEL[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "NAVIGATIONPANE", VS_STATE_DEFAULT },
		{ 2, "CONTENTPANE", VS_STATE(STATES_CONTROLPANEL_CONTENTPANE) },
		{ 3, "NAVPANELLABEL", VS_STATE_DEFAULT },
		{ 4, "CONTENTPANELLABEL", VS_STATE_DEFAULT },
		{ 5, "TITLE", VS_STATE_DEFAULT },
		{ 6, "BODYTEXT", VS_STATE_DEFAULT },
		{ 7, "HELPLINK", VS_STATE(STATES_LINK_HELP) },
		{ 8, "TASKLIST", VS_STATE(STATES_LINK_TASK) },
		{ 9, "GROUPTEXT", VS_STATE_DEFAULT },
		{ 10, "CONTENTLINK", VS_STATE(STATES_LINK_CONTENT) },
		{ 11, "SECIONTITLELINK", VS_STATE(STATES_LINK_SECTIONTITLE) },
		{ 12, "LARGECOMMANDAREA", VS_STATE_DEFAULT },
		{ 13, "SMALLCOMMANDAREA", VS_STATE_DEFAULT },
		{ 14, "BUTTON", VS_STATE_DEFAULT },
		{ 15, "MESSAGETEXT", VS_STATE_DEFAULT },
		{ 16, "NAVIGATIONPANELINE", VS_STATE_DEFAULT },
		{ 17, "CONTENTPANELINE", VS_STATE_DEFAULT },
		{ 18, "BANNERAREA", VS_STATE_DEFAULT },
		{ 19, "BODYTITLE", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_COPYCLOSE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "COPYCLOSEBTN", VS_STATE(STATES_COPYCLOSEBTN) },
	};

	const PartMap PARTS_DROPLIST[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "MENUBUTTON", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_EMPTYMARKUP[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "MARKUPTEXT", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_EXPLORERBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "HEADERBACKGROUND", VS_STATE_DEFAULT },
		{ 2, "HEADERCLOSE", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 3, "HEADERPIN", VS_STATE(STATES_EXPLORERBAR_HDRPIN) },
		{ 4, "IEBARMENU", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 5, "NORMALGROUPBACKGROUND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 6, "NORMALGROUPCOLLAPSE", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 7, "NORMALGROUPEXPAND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 8, "NORMALGROUPHEAD", VS_STATE_DEFAULT },
		{ 9, "SPECIALGROUPBACKGROUND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 10, "SPECIALGROUPCOLLAPSE", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 11, "SPECIALGROUPEXPAND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 12, "SPECIALGROUPHEAD", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_INFOBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "FOREGROUND", VS_STATE_DEFAULT }, // W10
	};

	const PartMap PARTS_ITEMSVIEW[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "SEARCHHIT", VS_STATE(STATES_ITEMSVIEW_SEARCHHIT) },
		{ 2, "SUBSETBUTTON", VS_STATE_DEFAULT },
		{ 3, "FOCUSRECT", VS_STATE(STATES_ITEMSVIEW_FOCUSRECT) },
		{ 4, "PROPERTY", VS_STATE(STATES_ITEMSVIEW_PROPERTY) },
		{ 5, "EMPTYTEXT", VS_STATE_DEFAULT },
		{ 6, "FOCUSRECTINNER", VS_STATE(STATES_ITEMSVIEW_FOCUSRECT) }, // W10
	};

	const PartMap PARTS_LISTBOX[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BORDER_HSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 2, "BORDER_HVSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 3, "BORDER_NOSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 4, "BORDER_VSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 5, "ITEM", VS_STATE(STATES_LISTBOX_ITEMS) },
	};

	const PartMap PARTS_LISTVIEW[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "LISTITEM", VS_STATE(STATES_LISTVIEW_ITEMS) },
		{ 2, "LISTGROUP", VS_STATE_DEFAULT },
		{ 3, "LISTDETAIL", VS_STATE_DEFAULT },
		{ 4, "LISTSORTEDDETAIL", VS_STATE_DEFAULT },
		{ 5, "EMPTYTEXT", VS_STATE_DEFAULT },
		{ 6, "GROUPHEADER", VS_STATE(STATES_LISTVIEW_GROUPHEADER_GENERAL) },
		{ 7, "GROUPHEADERLINE", VS_STATE(STATES_LISTVIEW_GROUPHEADER_GENERAL) },
		{ 8, "EXPANDBUTTON", VS_STATE(STATES_LISTVIEW_EXPCOLLAPSE) },
		{ 9, "COLLAPSEBUTTON", VS_STATE(STATES_LISTVIEW_EXPCOLLAPSE) },
		{ 10, "COLUMNDETAIL", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_LINK[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "HyperLink", VS_STATE(STATES_TOOLTIP_BALLOON_AND_STANDARD) }, // reuse states
	};

	const PartMap PARTS_MENU[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "MENUITEM", VS_STATE_DEFAULT },
		{ 2, "MENUDROPDOWN", VS_STATE_DEFAULT },
		{ 3, "MENUBARITEM", VS_STATE(STATES_MENU_BARITEM) },
		{ 4, "MENUBARDROPDOWN", VS_STATE_DEFAULT },
		{ 5, "CHEVRON", VS_STATE_DEFAULT },
		{ 6, "SEPARATOR", VS_STATE_DEFAULT },
		{ 7, "BARBACKGROUND", VS_STATE_DEFAULT },
		{ 8, "BARITEM", VS_STATE(STATES_MENU_BARITEM) },
		{ 9, "POPUPBACKGROUND", VS_STATE_DEFAULT },
		{ 10, "POPUPBORDERS", VS_STATE_DEFAULT },
		{ 11, "POPUPCHECK", VS_STATE(STATES_MENU_POPCHECK) },
		{ 12, "POPUPCHECKBACKGROUND", VS_STATE(STATES_MENU_POPCHECKBG) },
		{ 13, "POPUPGUTTER", VS_STATE_DEFAULT },
		{ 14, "POPUPITEM", VS_STATE(STATES_MENU_POPITEMS) },
		{ 15, "POPUPSEPARATOR", VS_STATE_DEFAULT },
		{ 16, "POPUPSUBMENU", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 17, "SYSTEMCLOSE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 18, "SYSTEMMAXIMIZE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 19, "SYSTEMMINIMIZE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 20, "SYSTEMRESTORE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
	};

	const PartMap PARTS_NAVIGATION[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKBUTTON", VS_STATE(STATES_PUSHBUTTON) }, // reuse button states
		{ 2, "FORWARDBUTTON", VS_STATE(STATES_PUSHBUTTON) },
		{ 3, "MENUBUTTON", VS_STATE(STATES_PUSHBUTTON) },
	};

	const PartMap PARTS_TREEVIEW[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TREEITEM", VS_STATE(STATES_TREEVIEW_ITEM) },
		{ 2, "GLYPH", VS_STATE(STATES_TREEVIEW_GLYPH) },
		{ 3, "BRANCH", VS_STATE_DEFAULT },
		{ 4, "HOTGLYPH", VS_STATE(STATES_TREEVIEW_GLYPH) },
	};

	const PartMap PARTS_WINDOW[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "CAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 2, "SMALLCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 3, "MINCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 4, "SMALLMINCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 5, "MAXCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 6, "SMALLMAXCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 7, "FRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 8, "FRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 9, "FRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 10, "SMALLFRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 11, "SMALLFRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 12, "SMALLFRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 13, "SYSBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "MDISYSBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "MINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "MDIMINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "MAXBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "CLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "SMALLCLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "MDICLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "RESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MDIRESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "HELPBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MDIHELPBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "HORZSCROLL", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "HORZTHUMB", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "VERTSCROLL", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "VERTTHUMB", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "DIALOG", VS_STATE_DEFAULT },
		{ 30, "CAPTIONSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 31, "SMALLCAPTIONSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 32, "FRAMELEFTSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 33, "SMALLFRAMELEFTSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 34, "FRAMERIGHTSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 35, "SMALLFRAMERIGHTSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 36, "FRAMEBOTTOMSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 37, "SMALLFRAMEBOTTOMSIZINGTEMPLATE", VS_STATE_DEFAULT },
		{ 38, "FRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 39, "BORDER", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_DWMPEN[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PENBARREL", VS_STATE_DEFAULT },
		{ 2, "PENHOLD", VS_STATE_DEFAULT },
		{ 3, "PENRIGHTTAP", VS_STATE_DEFAULT },
		{ 4, "PENTAP", VS_STATE_DEFAULT },
		{ 5, "PENDOUBLETAP", VS_STATE_DEFAULT },
		{ 6, "FLICKSCROLLUP", VS_STATE_DEFAULT },
		{ 7, "FLICKSCROLLDOWN", VS_STATE_DEFAULT },
		{ 8, "FLICKDRAGUP", VS_STATE_DEFAULT },
		{ 9, "FLICKDRAGDOWN", VS_STATE_DEFAULT },
		{ 10, "FLICKFORWARD", VS_STATE_DEFAULT },
		{ 11, "FLICKBACKWARD", VS_STATE_DEFAULT },
		{ 12, "FLICKCUT", VS_STATE_DEFAULT },
		{ 13, "FLICKCOPY", VS_STATE_DEFAULT },
		{ 14, "FLICKPASTE", VS_STATE_DEFAULT },
		{ 15, "FLICKUNDO", VS_STATE_DEFAULT },
		{ 16, "FLICKREDO", VS_STATE_DEFAULT },
		{ 17, "FLICKPRINT", VS_STATE_DEFAULT },
		{ 18, "FLICKDELETE", VS_STATE_DEFAULT },
		{ 19, "FLICKOPEN", VS_STATE_DEFAULT },
		{ 20, "FLICKSAVE", VS_STATE_DEFAULT },
		{ 21, "FLICKMODIFIERKEY", VS_STATE_DEFAULT },
		{ 22, "FLICKSHIFTKEY", VS_STATE_DEFAULT },
		{ 23, "FLICKWINKEY", VS_STATE_DEFAULT },
		{ 24, "FLICKGENERICKEY", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_DWMTOUCH[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TOUCHDRAG", VS_STATE_DEFAULT },
		{ 2, "TOUCHCONTACT", VS_STATE_DEFAULT },
		{ 3, "TETHER", VS_STATE_DEFAULT },
		{ 4, "TEXTHANDLEBLACK", VS_STATE_DEFAULT },
		{ 5, "TEXTHANDLEWHITE", VS_STATE_DEFAULT },
		{ 6, "TOUCHDOUBLECONTACT", VS_STATE_DEFAULT },
		{ 7, "TOUCHCONTACTPRESENTATIONMODE", VS_STATE_DEFAULT },
		{ 8, "INDIRECTTOUCH", VS_STATE_DEFAULT },
	};

	// Uses custom naming.
	const PartMap PARTS_DWMWINDOW_WIN7[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "FRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 2, "FRAMEBOTTOMSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 3, "RESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "RESTOREBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "MINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "MINBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "CLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "CLOSEBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "CLOSEBUTTON_ONLY", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "CLOSEBUTTON_ONLY", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "CLOSEBUTTONGLOW", VS_STATE_DEFAULT },
		{ 12, "CLOSEBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "CLOSEBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "CLOSEBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "CLOSEBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "MINMAXBUTTONGLOW", VS_STATE_DEFAULT },
		{ 17, "HELPBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "HELPBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "HELPBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "HELPBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "MAXBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MAXBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "MAXBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MAXBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "MINBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "MINBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "MINBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "MINBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "RESTOREBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "RESTOREBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "RESTOREBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 32, "RESTOREBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 33, "FRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 34, "FRAMELEFT_EFFECT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 35, "FRAMELEFTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 36, "FRAMEBOTTOMFADE", VS_STATE_DEFAULT },
		{ 37, "FRAMELEFTFADE", VS_STATE_DEFAULT },
		{ 38, "FRAMERIGHTFADE", VS_STATE_DEFAULT },
		{ 39, "FRAMETOPFADE", VS_STATE_DEFAULT },
		{ 40, "REFLECTIONS", VS_STATE_DEFAULT },
		{ 41, "FRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 42, "FRAMERIGHTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 43, "SIDEHIGHLIGHT", VS_STATE_DEFAULT },
		{ 44, "TOOLFRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TOOLCLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 46, "TOOLCLOSEBUTTON_INACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 47, "TOOLCLOSEBUTTONGLOW", VS_STATE_DEFAULT },
		{ 48, "TOOLCLOSEBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 49, "TOOLCLOSEBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 50, "TOOLCLOSEBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 51, "TOOLCLOSEBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 52, "TOOLFRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 53, "TOOLFRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 54, "TOOLFRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 55, "TEXTGLOW", VS_STATE_DEFAULT },
		{ 56, "FRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 57, "FRAMETOPSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 58, "FRAMETOP_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 59, "FRAMEBOTTOM_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 60, "FRAMELEFT_PEEK", VS_STATE_DEFAULT },
		{ 61, "FRAMERIGHT_PEEK", VS_STATE_DEFAULT },
		{ 62, "FRAMETOP_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 63, "FRAMEBOTTOM_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 64, "TOOLFRAMELEFT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 65, "TOOLFRAMERIGHT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 66, "TOOLFRAMETOP_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 67, "TOOLFRAMEBOTTOM_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 68, "SPINNER", VS_STATE_DEFAULT },
		{ 69, "SNAPINDICATOR", VS_STATE_DEFAULT },
		{ 70, "FRAMETOP_SELECTED", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 71, "FRAMEBOTTOM_SELECTED", VS_STATE(STATES_WINDOW_FRAME_GEN) },
	};

	// Incomplete and maybe incorrect list of parts for Win 8.1, derived from W7
	// and guesswork?? Can't remember. Uses custom naming.. TODO: consult PDBs
	const PartMap PARTS_DWMWINDOW_WIN81[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "FRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 2, "FRAMEBOTTOMSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 3, "RESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "RESTOREBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "MINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "MINBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "CLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "CLOSEBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "CLOSEBUTTON_ONLY", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "CLOSEBUTTON_ONLY_INACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "Part 11", VS_STATE_DEFAULT },
		{ 12, "CLOSEBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "CLOSEBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "CLOSEBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "CLOSEBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "HELPBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "HELPBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "HELPBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "HELPBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "MAXBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "MAXBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MAXBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "MAXBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MINBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "MINBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "MINBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "MINBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "RESTOREBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "RESTOREBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "RESTOREBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "RESTOREBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 32, "FRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 33, "FRAMELEFTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 34, "FRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 35, "FRAMERIGHTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 36, "TOOLFRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 37, "TOOLCLOSE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 38, "TOOLCLOSEINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 39, "TOOLCLOSEGLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 40, "TOOLCLOSEGLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 41, "TOOLCLOSEGLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 42, "TOOLCLOSEGLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 43, "TOOLFRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 44, "TOOLFRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TOOLFRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 46, "TEXTGLOW", VS_STATE_DEFAULT },
		{ 47, "FRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 48, "FRAMETOPSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 49, "FRAMETOP_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 50, "FRAMEBOTTOM_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 51, "FRAMELEFT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 52, "FRAMERIGHT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 53, "FRAMETOP_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 54, "FRAMEBOTTOM_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 55, "TOOLFRAMELEFT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 56, "TOOLFRAMERIGHT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 57, "TOOLFRAMETOP_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 58, "TOOLFRAMEBOTTOM_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 59, "SPINNER", VS_STATE_DEFAULT },
		{ 60, "SNAPINDICATOR", VS_STATE_DEFAULT },
		{ 61, "FRAMETOP_NOSHADOW_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 62, "FRAMEBOTTOM_NOSHADOW_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 63, "FRAMEBACKGROUND_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) }
	};

	// Definitive parts for W10, using the real names from the PDBs
	// States are generic and might not match every part.
	const PartMap PARTS_DWMWINDOW_WIN10[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BOTTOMFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 2, "BOTTOMSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 3, "BUTTONACTIVECAPTION", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "BUTTONINACTIVECAPTION", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "BUTTONACTIVECAPTIONEND", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "BUTTONINACTIVECAPTIONEND", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "BUTTONACTIVECLOSE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "BUTTONINACTIVECLOSE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "BUTTONACTIVECLOSEALONE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "BUTTONINACTIVECLOSEALONE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "BUTTONCLOSEGLYPH96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 12, "BUTTONCLOSEGLYPH120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "BUTTONCLOSEGLYPH144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "BUTTONCLOSEGLYPH192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "BUTTONHELPGLYPH96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "BUTTONHELPGLYPH120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "BUTTONHELPGLYPH144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "BUTTONHELPGLYPH192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "BUTTONMAXGLYPH96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "BUTTONMAXGLYPH120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "BUTTONMAXGLYPH144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "BUTTONMAXGLYPH192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "BUTTONMINGLYPH96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "BUTTONMINGLYPH120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "BUTTONMINGLYPH144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "BUTTONMINGLYPH192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "BUTTONRESTOREGLYPH96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "BUTTONRESTOREGLYPH120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "BUTTONRESTOREGLYPH144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "BUTTONRESTOREGLYPH192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "LEFTFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 32, "LEFTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 33, "RIGHTFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 34, "RIGHTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 35, "SMALLBOTTOMFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 36, "SMALLBUTTONACTIVECLOSE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 37, "SMALLBUTTONINACTIVECLOSE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 38, "SMALLBUTTONCLOSEGLYPH96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 39, "SMALLBUTTONCLOSEGLYPH120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 40, "SMALLBUTTONCLOSEGLYPH144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 41, "SMALLBUTTONCLOSEGLYPH192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 42, "SMALLLEFTFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 43, "SMALLRIGHTFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 44, "SMALLTOPFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TEXTGLOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 46, "TOPFRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 47, "TOPSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 48, "TOPFRAMENOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 49, "BOTTOMFRAMENOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 50, "LEFTFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 51, "RIGHTFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 52, "TOPFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 53, "BOTTOMFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 54, "SMALLLEFTFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 55, "SMALLRIGHTFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 56, "SMALLTOPFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 57, "SMALLBOTTOMFRAMESQUEEGEE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 58, "BITMAPPENDING", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 59, "RIPPLE", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 60, "TOPFRAMESQUEEGEENOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 61, "BOTTOMFRAMESQUEEGEENOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 62, "SQUEEGEEREFLECTIONMAP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 63, "THUMBNAILBORDER", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 64, "BUTTONCLOSEGLYPH96DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 65, "BUTTONCLOSEGLYPH120DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 66, "BUTTONCLOSEGLYPH144DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 67, "BUTTONCLOSEGLYPH192DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 68, "BUTTONHELPGLYPH96DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 69, "BUTTONHELPGLYPH120DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 70, "BUTTONHELPGLYPH144DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 71, "BUTTONHELPGLYPH192DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 72, "BUTTONMAXGLYPH96DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 73, "BUTTONMAXGLYPH120DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 74, "BUTTONMAXGLYPH144DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 75, "BUTTONMAXGLYPH192DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 76, "BUTTONMINGLYPH96DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 77, "BUTTONMINGLYPH120DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 78, "BUTTONMINGLYPH144DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 79, "BUTTONMINGLYPH192DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 80, "BUTTONRESTOREGLYPH96DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 81, "BUTTONRESTOREGLYPH120DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 82, "BUTTONRESTOREGLYPH144DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 83, "BUTTONRESTOREGLYPH192DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 84, "SMALLBUTTONCLOSEGLYPH96DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 85, "SMALLBUTTONCLOSEGLYPH120DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 86, "SMALLBUTTONCLOSEGLYPH144DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 87, "SMALLBUTTONCLOSEGLYPH192DARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 88, "BUTTONACTIVECAPTIONDARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 89, "BUTTONINACTIVECAPTIONDARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 90, "BUTTONACTIVECAPTIONENDDARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 91, "BUTTONINACTIVECAPTIONENDDARK", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
	};

	const PartMap PARTS_EDIT[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "EDITTEXT", VS_STATE(STATES_EDITTEXT) },
		{ 2, "CARET", VS_STATE_DEFAULT },
		{ 3, "BACKGROUND", VS_STATE(STATES_EDITTEXT_BG) },
		{ 4, "PASSWORD", VS_STATE_DEFAULT },
		{ 5, "BACKGROUNDWITHBORDER", VS_STATE(STATES_EDITTEXT_BGWITHBORDER) },
		{ 6, "EDITBORDER_NOSCROLL", VS_STATE(STATES_EDITTEXT_GENERAL) },
		{ 7, "EDITBORDER_HSCROLL", VS_STATE(STATES_EDITTEXT_GENERAL) },
		{ 8, "EDITBORDER_VSCROL", VS_STATE(STATES_EDITTEXT_GENERAL) },
		{ 9, "EDITBORDER_HVSCROLL", VS_STATE(STATES_EDITTEXT_GENERAL) },
	};

	const PartMap PARTS_TASKDIALOG[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PRIMARYPANEL", VS_STATE_DEFAULT },
		{ 2, "MAININSTRUCTIONPANE", VS_STATE_DEFAULT },
		{ 3, "MAINICON", VS_STATE_DEFAULT },
		{ 4, "CONTENTPANE", VS_STATE_DEFAULT },
		{ 5, "CONTENTICON", VS_STATE_DEFAULT },
		{ 6, "EXPANDEDCONTENT", VS_STATE_DEFAULT },
		{ 7, "COMMANDLINKPANE", VS_STATE_DEFAULT },
		{ 8, "SECONDARYPANEL", VS_STATE_DEFAULT },
		{ 9, "CONTROLPANE", VS_STATE_DEFAULT },
		{ 10, "BUTTONSECTION", VS_STATE_DEFAULT },
		{ 11, "BUTTONWRAPPER", VS_STATE_DEFAULT },
		{ 12, "EXPANDOTEXT", VS_STATE_DEFAULT },
		{ 13, "EXPANDOBUTTON", VS_STATE(STATES_TASKDLG_EXPANDOBUTTON) },
		{ 14, "VERIFICATIONTEXT", VS_STATE_DEFAULT },
		{ 15, "FOOTNOTEPANE", VS_STATE_DEFAULT },
		{ 16, "FOOTNOTEAREA", VS_STATE_DEFAULT },
		{ 17, "FOOTNOTESEPARATOR", VS_STATE_DEFAULT },
		{ 18, "EXPANDEDFOOTERAREA", VS_STATE_DEFAULT },
		{ 19, "PROGRESSBAR", VS_STATE_DEFAULT },
		{ 20, "IMAGEALIGNMENT", VS_STATE_DEFAULT },
		{ 21, "RADIOBUTTONPANE", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_HEADER[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "HEADERITEM", VS_STATE(STATES_HEADER_ITEMSTATES) },
		{ 2, "HEADERITEMLEFT", VS_STATE(STATES_HEADER_LEFT_AND_RIGHT) },
		{ 3, "HEADERITEMRIGHT", VS_STATE(STATES_HEADER_LEFT_AND_RIGHT) },
		{ 4, "HEADERSORTARROW", VS_STATE(STATES_HEADERSORTARROWSTATES) },
		{ 5, "HEADERDROPDOWN", VS_STATE(STATES_HEADERDROPDOWNSTATES) },
		{ 6, "HEADERDROPDOWNFILTER", VS_STATE(STATES_HEADERDROPDOWNFILTERSTATES) },
		{ 7, "HEADEROVERFLOW", VS_STATE(STATES_HEADEROVERFLOWSTATES) },
	};

	const PartMap PARTS_READINGPANE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUNDCOLORS", VS_STATE_DEFAULT },
		{ 2, "LABEL", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_REBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "GRIPPER", VS_STATE_DEFAULT },
		{ 2, "GRIPPERVERT", VS_STATE_DEFAULT },
		{ 3, "BAND", VS_STATE_DEFAULT },
		{ 4, "CHEVRON", VS_STATE(STATES_REBAR_GENERAL) },
		{ 5, "CHEVRONVERT", VS_STATE(STATES_REBAR_GENERAL) },
		{ 6, "BACKGROUND", VS_STATE_DEFAULT },
		{ 7, "SPLITTER", VS_STATE(STATES_REBAR_GENERAL) },
		{ 8, "SPLITTERVERT", VS_STATE(STATES_REBAR_GENERAL) },
	};

	const PartMap PARTS_AEROWIZARD[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TITLEBAR", VS_STATE(STATES_WINDOW_FRAME_GEN) }, // reuse
		{ 2, "HEADERAREA", VS_STATE(STATES_AEROWIZARD_HEADERAREA) },
		{ 3, "CONTENTAREA", VS_STATE(STATES_AEROWIZARD_HEADERAREA) },
		{ 4, "COMMANDAREA", VS_STATE_DEFAULT },
		{ 5, "BUTTON", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_PAUSE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PAUSEBUTTON", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_PROGRESS[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BAR", VS_STATE_DEFAULT },
		{ 2, "BARVERT", VS_STATE_DEFAULT },
		{ 3, "CHUNK", VS_STATE_DEFAULT },
		{ 4, "CHUNKVERT", VS_STATE_DEFAULT },
		{ 5, "FILL", VS_STATE(STATES_PROGRESS_FILL_GENERAL) },
		{ 6, "FILLVERT", VS_STATE(STATES_PROGRESS_FILL_GENERAL) },
		{ 7, "PULSEOVERLAY", VS_STATE_DEFAULT },
		{ 8, "MOVEOVERLAY", VS_STATE_DEFAULT },
		{ 9, "PULSEOVERLAYVERT", VS_STATE_DEFAULT },
		{ 10, "MOVEOVERLAYVERT", VS_STATE_DEFAULT },
		{ 11, "TRANSPARENTBAR", VS_STATE(STATES_PROGRESS_TRANSPARENT_GENERAL) },
		{ 12, "TRANSPARENTBARVERT", VS_STATE(STATES_PROGRESS_TRANSPARENT_GENERAL) },
	};

	const PartMap PARTS_PROPERTREE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "FOLDERSHEADER", VS_STATE_DEFAULT },
		{ 2, "BACKGROUND", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_PREVIEWPANE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PREVIEWBACKGROUND", VS_STATE_DEFAULT },
		{ 2, "EDITPROPERTIES", VS_STATE_DEFAULT },
		{ 3, "NAVPANESIZER", VS_STATE_DEFAULT },
		{ 4, "READINGPANESIZER", VS_STATE_DEFAULT },
		{ 5, "TITLE", VS_STATE(STATES_PROGRESS_FILL_GENERAL) },
		{ 6, "LABEL", VS_STATE(STATES_PROGRESS_FILL_GENERAL) },
		{ 7, "VALUE", VS_STATE_DEFAULT },
		{ 8, "LABELCID", VS_STATE_DEFAULT },
		{ 9, "VALUECID", VS_STATE_DEFAULT }
	};

	const PartMap PARTS_TRACKBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TRACK", VS_STATE(STATES_TRACKBAR_GENERAL) },
		{ 2, "TRACKVERT", VS_STATE(STATES_TRACKBAR_GENERAL) },
		{ 3, "THUMB", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 4, "THUMBBOTTOM", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 5, "THUMBTOP", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 6, "THUMBVERT", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 7, "THUMBLEFT", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 8, "THUMBRIGHT", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 9, "TICS", VS_STATE(STATES_TRACKBAR_GENERAL) },
		{ 10, "TICSVERT", VS_STATE(STATES_TRACKBAR_GENERAL) },
	};

	const PartMap PARTS_TAB[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TABITEM", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 2, "TABITEMLEFTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 3, "TABITEMRIGHTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 4, "TABITEMBOTHEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 5, "TOPTABITEM", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 6, "TOPTABITEMLEFTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 7, "TOPTABITEMRIGHTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 8, "TOPTABITEMBOTHEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 9, "PANE", VS_STATE_DEFAULT },
		{ 10, "BODY", VS_STATE_DEFAULT },
		{ 11, "AEROWIZARDBODY", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TOOLTIP[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "STANDARD", VS_STATE(STATES_TOOLTIP_BALLOON_AND_STANDARD) },
		{ 2, "STANDARDTITLE", VS_STATE_DEFAULT },
		{ 3, "BALLOON", VS_STATE(STATES_TOOLTIP_BALLOON_AND_STANDARD) },
		{ 4, "BALLOONTITLE", VS_STATE_DEFAULT },
		{ 5, "CLOSE", VS_STATE(STATES_TOOLTIP_CLOSE) },
		{ 6, "BALLOONSTEM", VS_STATE(STATES_TOOLTIP_BALLOONSTEM) },
		{ 7, "WRENCH", VS_STATE(STATES_TOOLTIP_WRENCH) },
	};

	const PartMap PARTS_TOOLBAR[] =
	{
		{ 0, "Common Properties", VS_STATE(STATES_TOOLBARSTYLE) },
		{ 1, "BUTTON", VS_STATE_DEFAULT },
		{ 2, "DROPDOWNBUTTON", VS_STATE_DEFAULT },
		{ 3, "SPLITBUTTON", VS_STATE_DEFAULT },
		{ 4, "SPLITBUTTONDROPDOWN", VS_STATE_DEFAULT },
		{ 5, "SEPARATOR", VS_STATE_DEFAULT },
		{ 6, "SEPARATORVERT", VS_STATE_DEFAULT },
		{ 7, "DROPDOWNBUTTONGLYPH", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TASKBARPEARL[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PEARLICON", VS_STATE_DEFAULT },
		{ 2, "TABLETMODEPEARLICON", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TASKBARSHOWDESKTOP[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "SHOWDESKTOPTHEME", VS_STATE_DEFAULT },
		{ 2, "DIVIDERLINE", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TASKBAND[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "GROUPCONTENT", VS_STATE_DEFAULT },
		{ 2, "FLASHBUTTON", VS_STATE_DEFAULT },
		{ 3, "FLASHBUTTONGROUPMENU", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TASKBAND2[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BARTOP", VS_STATE_DEFAULT },
		{ 2, "BARBOTTOM", VS_STATE_DEFAULT },
		{ 3, "BARRIGHT", VS_STATE_DEFAULT },
		{ 4, "BARLEFT", VS_STATE_DEFAULT },
		{ 5, "TASKITEM", VS_STATE_DEFAULT },
		{ 6, "TASKITEMLEFT", VS_STATE_DEFAULT },
		{ 7, "TASKITEMCENTER", VS_STATE_DEFAULT },
		{ 8, "TASKITEMRIGHT", VS_STATE_DEFAULT },
		{ 9, "PROGRESSITEM", VS_STATE_DEFAULT },
		{ 10, "PROGRESSITEMINDETERMINATE", VS_STATE_DEFAULT },
		{ 11, "PROGRESSITEMERROR", VS_STATE_DEFAULT },
		{ 12, "PROGRESSITEMPAUSED", VS_STATE_DEFAULT },
		{ 13, "TASKITEMGROUP", VS_STATE_DEFAULT },
		{ 14, "TASKITEMGROUPSELECTED", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TASKBANDEXUI[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "BACKGROUNDSHADOW", VS_STATE_DEFAULT },
		{ 3, "THUMBRECT", VS_STATE_DEFAULT },
		{ 4, "WINDOWTEXT", VS_STATE_DEFAULT },
		{ 5, "SHADOW", VS_STATE_DEFAULT },
		{ 6, "ACTIVERECT", VS_STATE_DEFAULT },
		{ 7, "PREVACTIVERECT", VS_STATE_DEFAULT },
		{ 8, "THUMBBARBUTTONSINGLE", VS_STATE_DEFAULT },
		{ 9, "THUMBBARBUTTONLEFT", VS_STATE_DEFAULT },
		{ 10, "THUMBBARBUTTONMIDDLE", VS_STATE_DEFAULT },
		{ 11, "THUMBBARBUTTONRIGHT", VS_STATE_DEFAULT },
		{ 12, "CLOSEBUTTON", VS_STATE_DEFAULT },
		{ 13, "ARROWBUTTON", VS_STATE_DEFAULT },
		{ 14, "THUMBSHADOWRIGHT", VS_STATE_DEFAULT },
		{ 15, "THUMBSHADOWBOTTOM", VS_STATE_DEFAULT },
		{ 16, "WINDOWBORDER", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TASKMANAGER[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "ROW", VS_STATE_DEFAULT },
		{ 2, "COLUMNDIVIDER", VS_STATE_DEFAULT },
		{ 3, "HEATMAP_COLOR0", VS_STATE_DEFAULT },
		{ 4, "HEATMAP_COLOR1", VS_STATE_DEFAULT },
		{ 5, "HEATMAP_COLOR2", VS_STATE_DEFAULT },
		{ 6, "HEATMAP_COLOR3", VS_STATE_DEFAULT },
		{ 7, "HEATMAP_COLOR4", VS_STATE_DEFAULT },
		{ 8, "HEATMAP_COLOR5", VS_STATE_DEFAULT },
		{ 9, "HEATMAP_COLOR6", VS_STATE_DEFAULT },
		{ 10, "HEATMAP_COLOR7", VS_STATE_DEFAULT },
		{ 11, "HEATMAP_COLOR8", VS_STATE_DEFAULT },
		{ 12, "HEATMAP_CONTENTIONMARKER", VS_STATE_DEFAULT },
		{ 13, "HEATMAP_TEXT", VS_STATE_DEFAULT },
		{ 14, "RESOURCE_TITLE", VS_STATE_DEFAULT },
		{ 15, "RESOURCE_SUBTITLE", VS_STATE_DEFAULT },
		{ 16, "GROUPLABEL", VS_STATE_DEFAULT },
		{ 17, "STATICLABEL", VS_STATE_DEFAULT },
		{ 18, "STATICDATA", VS_STATE_DEFAULT },
		{ 19, "DYNAMICDATA", VS_STATE_DEFAULT },
		{ 20, "MEMORYBAR_AVAILABLE", VS_STATE_DEFAULT },
		{ 21, "MEMORYBAR_INUSE", VS_STATE_DEFAULT },
		{ 22, "MEMORYBAR_MODIFIED", VS_STATE_DEFAULT },
		{ 23, "MEMORYBAR_INUSE_SEPARATOR", VS_STATE_DEFAULT },
		{ 24, "COLUMNHEADERTEXT", VS_STATE_DEFAULT },
		{ 25, "CPU_HEATMAP_TEXT", VS_STATE_DEFAULT },
		{ 26, "CPU_HEATMAP_COLOR0", VS_STATE_DEFAULT },
		{ 27, "CPU_HEATMAP_COLOR1", VS_STATE_DEFAULT },
		{ 28, "CPU_HEATMAP_COLOR2", VS_STATE_DEFAULT },
		{ 29, "CPU_HEATMAP_COLOR3", VS_STATE_DEFAULT },
		{ 30, "CPU_HEATMAP_COLOR4", VS_STATE_DEFAULT },
		{ 31, "CPU_HEATMAP_COLOR5", VS_STATE_DEFAULT },
		{ 32, "CPU_HEATMAP_PARKED0", VS_STATE_DEFAULT },
		{ 33, "CPU_HEATMAP_PARKED1", VS_STATE_DEFAULT },
		{ 34, "CPU_HEATMAP_PARKED2", VS_STATE_DEFAULT },
		{ 35, "CPU_HEATMAP_PARKED3", VS_STATE_DEFAULT },
		{ 36, "CPU_HEATMAP_PARKED4", VS_STATE_DEFAULT },
		{ 37, "CPU_HEATMAP_PARKED5", VS_STATE_DEFAULT },
		{ 38, "CPU_HEATMAP_GRID_BORDER", VS_STATE_DEFAULT },
		{ 39, "CPU_HEATMAP_BLOCK_BORDER_R", VS_STATE_DEFAULT },
		{ 40, "CPU_HEATMAP_BLOCK_BORDER_B", VS_STATE_DEFAULT },
		{ 41, "COLHEADER_DIVIDER_COLOR1", VS_STATE_DEFAULT },
		{ 42, "COLHEADER_DIVIDER_COLOR2", VS_STATE_DEFAULT },
		{ 43, "CONTENTION_COLUMN_HEADER", VS_STATE(STATES_HEADEROVERFLOWSTATES) }, // reuse
		{ 44, "CHARTLEGEND", VS_STATE_DEFAULT },
		{ 45, "COLUMNDIVIDERSELECTED", VS_STATE_DEFAULT },
		{ 46, "COLUMNDIVIDERHOT", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TEXTSELECTIONGRIPPER[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "GRIPPER", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TEXTGLOW[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TEXTSTYLE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "MAININSTRUCTION", VS_STATE_DEFAULT },
		{ 2, "INSTRUCTION", VS_STATE_DEFAULT },
		{ 3, "BODYTITLE", VS_STATE_DEFAULT },
		{ 4, "BODYTEXT", VS_STATE_DEFAULT },
		{ 5, "SECONDARYTEXT", VS_STATE_DEFAULT },
		{ 6, "HYPERLINKTEXT", VS_STATE(STATES_TEXTSTYLE_HLINK) },
		{ 7, "EXPANDED", VS_STATE_DEFAULT },
		{ 8, "LABEL", VS_STATE_DEFAULT },
		{ 9, "CONTROLLABEL", VS_STATE(STATES_TEXTSTYLE_CTRLLABEL) },
	};

	const PartMap PARTS_TRAYNOTIFY[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "ANIMBACKGROUND", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_TRYHARDER[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BUTTON", VS_STATE_DEFAULT },
		{ 2, "VERTICAL", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_SPIN[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "UP", VS_STATE(STATES_SPIN_GENERAL) },
		{ 2, "DOWN", VS_STATE(STATES_SPIN_GENERAL) },
		{ 3, "UPHORZ", VS_STATE(STATES_SPIN_GENERAL) },
		{ 4, "DOWNHORZ", VS_STATE(STATES_SPIN_GENERAL) },
	};

	const PartMap PARTS_SEARCHBOX[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "CLEARBUTTON", VS_STATE(STATES_PUSHBUTTON) }, //W10
		{ 3, "SEARCHBUTTON", VS_STATE(STATES_PUSHBUTTON) }, //W10
	};

	const PartMap PARTS_SEARCHHOME[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "LINE", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_SCROLLBAR[] =
	{
		{ 0, "Common Properties", VS_STATE(STATES_SCROLLBAR_STYLE) },
		{ 1, "ARROWBTN", VS_STATE(STATES_SCROLLBAR_ARROWBTN) },
		{ 2, "THUMBBTNHORZ", VS_STATE_DEFAULT },
		{ 3, "THUMBBTNVERT", VS_STATE_DEFAULT },
		{ 4, "LOWERTRACKHORZ", VS_STATE_DEFAULT },
		{ 5, "UPPERTRACKHORZ", VS_STATE_DEFAULT },
		{ 6, "LOWERTRACKVERT", VS_STATE_DEFAULT },
		{ 7, "UPPERTRACKVERT", VS_STATE_DEFAULT },
		{ 8, "GRIPPERHORZ", VS_STATE_DEFAULT },
		{ 9, "GRIPPERVERT", VS_STATE_DEFAULT },
		{ 10, "SIZEBOX", VS_STATE(STATES_SCROLLBAR_SIZEBOX) },
	};

	const PartMap PARTS_STATIC[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "TEXT", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_STATUS[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "PANE", VS_STATE_DEFAULT },
		{ 2, "GRIPPERPANE", VS_STATE_DEFAULT },
		{ 3, "GRIPPER", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_FLYOUT[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "HEADER", VS_STATE(STATES_FLYOUT_HEADER) },
		{ 2, "BODY", VS_STATE(STATES_FLYOUT_BODY) },
		{ 3, "LABEL", VS_STATE(STATES_FLYOUT_LABEL) },
		{ 4, "LINK", VS_STATE(STATES_FLYOUT_LINK) },
		{ 5, "DIVIDER", VS_STATE_DEFAULT },
		{ 6, "WINDOW", VS_STATE_DEFAULT },
		{ 7, "LINKAREA", VS_STATE_DEFAULT },
		{ 8, "LINKHEADER", VS_STATE(STATES_FLYOUT_HEADER) },
	};

	const PartMap PARTS_DRAGDROP[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "COPY", VS_STATE(STATES_DND_GENERAL) },
		{ 2, "MOVE", VS_STATE(STATES_DND_GENERAL) },
		{ 3, "UPDATEMETADATA", VS_STATE(STATES_DND_GENERAL) },
		{ 4, "CREATELINK", VS_STATE(STATES_DND_GENERAL) },
		{ 5, "WARNING", VS_STATE(STATES_DND_GENERAL) },
		{ 6, "NONE", VS_STATE(STATES_DND_GENERAL) },
		{ 7, "IMAGEBG", VS_STATE_DEFAULT },
		{ 8, "TEXTBG", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_DATEPICKER[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "DATETEXT", VS_STATE(STATES_DATE_TEXT) },
		{ 2, "DATEBORDER", VS_STATE(STATES_DATE_BORDER) },
		{ 3, "SHOWCALENDARBUTTONRIGHT", VS_STATE(STATES_DATE_CALENDERBUTTONRIGHT) },
	};

	const PartMap PARTS_TASKBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUNDBOTTOM", VS_STATE_DEFAULT },
		{ 2, "BACKGROUNDRIGHT", VS_STATE_DEFAULT },
		{ 3, "BACKGROUNDTOP", VS_STATE_DEFAULT },
		{ 4, "BACKGROUNDLEFT", VS_STATE_DEFAULT },
		{ 5, "SIZINGBARBOTTOM", VS_STATE_DEFAULT },
		{ 6, "SIZINGBARRIGHT", VS_STATE_DEFAULT },
		{ 7, "SIZINGBARTOP", VS_STATE_DEFAULT },
		{ 8, "SIZINGBARLEFT", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_STARTPANEL[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "USERPANE", VS_STATE_DEFAULT },
		{ 2, "MOREPROGRAMS", VS_STATE_DEFAULT },
		{ 3, "MOREPROGRAMSARROW", VS_STATE_DEFAULT },
		{ 4, "PROGRAMLIST", VS_STATE_DEFAULT },
		{ 5, "PROGRAMLISTSEPARATOR", VS_STATE_DEFAULT },
		{ 6, "PLACELIST", VS_STATE_DEFAULT },
		{ 7, "PLACELISTSEPARATOR", VS_STATE_DEFAULT },
		{ 8, "LOGOFF", VS_STATE_DEFAULT },
		{ 9, "LOGOFFBUTTONS", VS_STATE_DEFAULT },
		{ 10, "USERPICTURE", VS_STATE_DEFAULT },
		{ 11, "PREVIEW", VS_STATE_DEFAULT },
		{ 12, "MOREPROGRAMSTAB", VS_STATE_DEFAULT },
		{ 13, "NSCHOST", VS_STATE_DEFAULT },
		{ 14, "SOFTWAREEXPLORER", VS_STATE_DEFAULT },
		{ 15, "OPENBOX", VS_STATE_DEFAULT },
		{ 16, "SEARCHVIEW", VS_STATE_DEFAULT },
		{ 17, "MOREPROGRAMSARROWBACK", VS_STATE_DEFAULT },
		{ 18, "TOPMATCH", VS_STATE_DEFAULT },
		{ 19, "LOGOFFSPLITBUTTONDROPDOWN", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_STARTPANELPRIV[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "USERPANE", VS_STATE_DEFAULT },
		{ 2, "MOREPROGRAMS", VS_STATE_DEFAULT },
		{ 3, "MOREPROGRAMSDEST", VS_STATE_DEFAULT },
		{ 4, "MOREPROGRAMSARROW", VS_STATE_DEFAULT },
		{ 5, "FLYOUTARROW", VS_STATE_DEFAULT },
		{ 6, "PROGRAMLIST", VS_STATE_DEFAULT },
		{ 7, "PROGRAMLIST2", VS_STATE_DEFAULT },
		{ 8, "PROGRAMLISTSEPARATOR", VS_STATE_DEFAULT },
		{ 9, "PLACESLIST", VS_STATE_DEFAULT },
		{ 10, "DESTLIST", VS_STATE_DEFAULT },
		{ 11, "PLACESLISTSEPARATOR", VS_STATE_DEFAULT },
		{ 12, "DESTINATIONMENUTOP", VS_STATE_DEFAULT },
		{ 13, "DESTINATIONMENUBOTTOM", VS_STATE_DEFAULT },
		{ 14, "LOGOFFBACKGROUND", VS_STATE_DEFAULT },
		{ 15, "LOGOFFDESTBACKGROUND", VS_STATE_DEFAULT },
		{ 16, "MOREPROGRAMSTAB", VS_STATE_DEFAULT },
		{ 17, "NSCHOST", VS_STATE_DEFAULT },
		{ 18, "OPENBOX", VS_STATE_DEFAULT },
		{ 19, "OPENBOXDEST", VS_STATE_DEFAULT },
		{ 20, "SEARCHVIEW", VS_STATE_DEFAULT },
		{ 21, "MOREPROGRAMSARROWBACK", VS_STATE_DEFAULT },
		{ 22, "TOPMATCH", VS_STATE_DEFAULT },
		{ 23, "LOGOFFSPLITBUTTONDROPDOWN", VS_STATE_DEFAULT },
		{ 24, "LOGOFFSPLITBUTTONDROPDOWNDEST", VS_STATE_DEFAULT },
		{ 25, "PINICON", VS_STATE_DEFAULT },
		{ 26, "SMALLPINOFFSET", VS_STATE_DEFAULT },
		{ 27, "LARGEPINOFFSET", VS_STATE_DEFAULT },
		{ 28, "LEFTMFUBUTTON", VS_STATE_DEFAULT },
		{ 29, "FULLMFUBUTTON", VS_STATE_DEFAULT },
		{ 30, "CENTERMFUBUTTON", VS_STATE_DEFAULT },
		{ 31, "RIGHTMFUBUTTON", VS_STATE_DEFAULT },
		{ 32, "FULLPLACESBUTTON", VS_STATE_DEFAULT },
		{ 33, "LEFTPLACESBUTTON", VS_STATE_DEFAULT },
		{ 34, "CENTERPLACESBUTTON", VS_STATE_DEFAULT },
		{ 35, "RIGHTPLACESBUTTON", VS_STATE_DEFAULT },
		{ 36, "SPECIALFOLDERSBUTTON", VS_STATE_DEFAULT },
		{ 37, "LOGOFFSPLITBUTTON", VS_STATE_DEFAULT },
		{ 38, "LOGOFFSPLITBUTTONDEST", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_MONTHCAL[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "BACKGROUND", VS_STATE_DEFAULT },
		{ 2, "BORDERS", VS_STATE_DEFAULT },
		{ 3, "GRIDBACKGROUND", VS_STATE_DEFAULT },
		{ 4, "COLHEADERSPLITTER", VS_STATE_DEFAULT },
		{ 5, "GRIDCELLBACKGROUND", VS_STATE(STATES_MONTHCAL_CELL) },
		{ 6, "GRIDCELL", VS_STATE(STATES_MONTHCAL_CELL) },
		{ 7, "GRIDCELLUPPER", VS_STATE(STATES_MONTHCAL_CELL) },
		{ 8, "TRAILINGGRIDCELL", VS_STATE(STATES_MONTHCAL_CELL) },
		{ 9, "TRAILINGGRIDCELLUPPER", VS_STATE(STATES_MONTHCAL_CELL) },
		{ 10, "NAVNEXT", VS_STATE_DEFAULT },
		{ 11, "NAVPREV", VS_STATE_DEFAULT },
	};

	const PartMap PARTS_USERTILE[] =
	{
		{ 0, "Common Properties", VS_STATE_DEFAULT },
		{ 1, "STROKEBACKGROUND", VS_STATE_DEFAULT },
		{ 2, "HOVERBACKGROUND", VS_STATE_DEFAULT },
	};
}