#pragma once

#include "VisualStyleParts.h"

#define AL(arr) (sizeof(arr) / sizeof(arr[0]))
#define VS_STATE(state) state, AL(state)
#define VS_STATE_NONE 0, 0

namespace libmsstyle
{
	const NameMap PARTS_BUTTON[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "PUSHBUTTON", VS_STATE(STATES_PUSHBUTTON) },
		{ 2, "RADIOBUTTON", VS_STATE(STATES_RADIOBUTTON) },
		{ 3, "CHECKBOX", VS_STATE(STATES_CHECKBOX) },
		{ 4, "GROUPBOX", VS_STATE(STATES_GROUPBOX) },
		{ 5, "USERBUTTON", VS_STATE_NONE },
		{ 6, "COMMANDLINK", VS_STATE(STATES_COMMANDLINK) },
		{ 7, "COMMANDLINKGLYPH", VS_STATE(STATES_COMMANDLINKGLYPHS) },
	};

	const NameMap PARTS_COMBOBOX[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "DROPDOWNBUTTON", VS_STATE_NONE },
		{ 2, "BACKGROUND", VS_STATE_NONE },
		{ 3, "TRANSPARENTBACKGROUND", VS_STATE(STATES_CB_TRANSPARENTBG) },
		{ 4, "BORDER", VS_STATE(STATES_CB_BORDER) },
		{ 5, "READONLY", VS_STATE(STATES_CB_READONLY) },
		{ 6, "DROPDOWNBUTTONRIGHT", VS_STATE(STATES_CB_DROPDOWNLR) },
		{ 7, "DROPDOWNBUTTONLEFT", VS_STATE(STATES_CB_DROPDOWNLR) },
		{ 8, "CUEBANNER", VS_STATE(STATES_CB_CUEBANNER) },
	};

	const NameMap PARTS_CONTROLPANEL[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "NAVIGATIONPANE", VS_STATE_NONE },
		{ 2, "CONTENTPANE", VS_STATE_NONE },
		{ 3, "NAVPANELLABEL", VS_STATE_NONE },
		{ 4, "CONTENTPANELLABEL", VS_STATE_NONE },
		{ 5, "TITLE", VS_STATE_NONE },
		{ 6, "BODYTEXT", VS_STATE_NONE },
		{ 7, "HELPLINK", VS_STATE(STATES_LINK_HELP) },
		{ 8, "TASKLIST", VS_STATE(STATES_LINK_TASK) },
		{ 9, "GROUPTEXT", VS_STATE_NONE },
		{ 10, "CONTENTLINK", VS_STATE(STATES_LINK_CONTENT) },
		{ 11, "SECIONTITLELINK", VS_STATE(STATES_LINK_SECTIONTITLE) },
		{ 12, "LARGECOMMANDAREA", VS_STATE_NONE },
		{ 13, "SMALLCOMMANDAREA", VS_STATE_NONE },
		{ 14, "BUTTON", VS_STATE_NONE },
		{ 15, "MESSAGETEXT", VS_STATE_NONE },
		{ 16, "NAVIGATIONPANELINE", VS_STATE_NONE },
		{ 17, "CONTENTPANELINE", VS_STATE_NONE },
		{ 18, "BANNERAREA", VS_STATE_NONE },
		{ 19, "BODYTITLE", VS_STATE_NONE },
	};

	const NameMap PARTS_EXPLORERBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "HEADERBACKGROUND", VS_STATE_NONE },
		{ 2, "HEADERCLOSE", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 3, "HEADERPIN", VS_STATE(STATES_EXPLORERBAR_HDRPIN) },
		{ 4, "IEBARMENU", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 5, "NORMALGROUPBACKGROUND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 6, "NORMALGROUPCOLLAPSE", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 7, "NORMALGROUPEXPAND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 8, "NORMALGROUPHEAD", VS_STATE_NONE },
		{ 9, "SPECIALGROUPBACKGROUND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 10, "SPECIALGROUPCOLLAPSE", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 11, "SPECIALGROUPEXPAND", VS_STATE(STATES_EXPLORERBAR_GENERAL) },
		{ 12, "SPECIALGROUPHEAD", VS_STATE_NONE },
	};

	const NameMap PARTS_LISTBOX[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "BORDER_HSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 2, "BORDER_HVSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 3, "BORDER_NOSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 4, "BORDER_VSCROLL", VS_STATE(STATES_LISTBOX_SCROLL) },
		{ 5, "ITEM", VS_STATE(STATES_LISTBOX_ITEMS) },
	};

	const NameMap PARTS_LISTVIEW[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "LISTITEM", VS_STATE(STATES_LISTVIEW_ITEMS) },
		{ 2, "LISTGROUP", VS_STATE_NONE },
		{ 3, "LISTDETAIL", VS_STATE_NONE },
		{ 4, "LISTSORTEDDETAIL", VS_STATE_NONE },
		{ 5, "EMPTYTEXT", VS_STATE_NONE },
		{ 6, "GROUPHEADER", VS_STATE(STATES_LISTVIEW_GROUPHEADER_GENERAL) },
		{ 7, "GROUPHEADERLINE", VS_STATE(STATES_LISTVIEW_GROUPHEADER_GENERAL) },
		{ 8, "EXPANDBUTTON", VS_STATE(STATES_LISTVIEW_EXPCOLLAPSE) },
		{ 9, "COLLAPSEBUTTON", VS_STATE(STATES_LISTVIEW_EXPCOLLAPSE) },
		{ 10, "COLUMNDETAIL", VS_STATE_NONE },
	};

	const NameMap PARTS_MENU[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "MENUITEM", VS_STATE_NONE },
		{ 2, "MENUDROPDOWN", VS_STATE_NONE },
		{ 3, "MENUBARITEM", VS_STATE(STATES_MENU_BARITEM) },
		{ 4, "MENUBARDROPDOWN", VS_STATE_NONE },
		{ 5, "CHEVRON", VS_STATE_NONE },
		{ 6, "SEPARATOR", VS_STATE_NONE },
		{ 7, "BARBACKGROUND", VS_STATE_NONE },
		{ 8, "BARITEM", VS_STATE(STATES_MENU_BARITEM) },
		{ 9, "POPUPBACKGROUND", VS_STATE_NONE },
		{ 10, "POPUPBORDERS", VS_STATE_NONE },
		{ 11, "POPUPCHECK", VS_STATE(STATES_MENU_POPCHECK) },
		{ 12, "POPUPCHECKBACKGROUND", VS_STATE(STATES_MENU_POPCHECKBG) },
		{ 13, "POPUPGUTTER", VS_STATE_NONE },
		{ 14, "POPUPITEM", VS_STATE(STATES_MENU_POPITEMS) },
		{ 15, "POPUPSEPARATOR", VS_STATE_NONE },
		{ 16, "POPUPSUBMENU", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 17, "SYSTEMCLOSE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 18, "SYSTEMMAXIMIZE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 19, "SYSTEMMINIMIZE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
		{ 20, "SYSTEMRESTORE", VS_STATE(STATES_MENU_SYSTEM_GENERAL) },
	};

	const NameMap PARTS_TREEVIEW[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "TREEITEM", VS_STATE(STATES_TREEVIEW_ITEM) },
		{ 2, "GLYPH", VS_STATE(STATES_TREEVIEW_GLYPH) },
		{ 3, "BRANCH", VS_STATE_NONE },
		{ 4, "HOTGLYPH", VS_STATE(STATES_TREEVIEW_GLYPH) },
	};

	const NameMap PARTS_WINDOW[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "CAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 2, "SMALLCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 3, "MINCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 4, "SMALLMINCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 5, "MAXCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 6, "SMALLMAXCAPTION", VS_STATE(STATES_WINDOW_CAPTION_GEN) },
		{ 7, "FRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 8, "FRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 9, "FRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 10, "SMALLFRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 11, "SMALLFRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 12, "SMALLFRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 13, "SYSBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "MDISYSBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "MINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "MDIMINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "MAXBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "CLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "SMALLCLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "MDICLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "RESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MDIRESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "HELPBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MDIHELPBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "HORZSCROLL", VS_STATE_NONE },
		{ 26, "HORZTHUMB", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "VERTSCROLL", VS_STATE_NONE },
		{ 28, "VERTTHUMB", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "DIALOG", VS_STATE_NONE },
		{ 30, "CAPTIONSIZINGTEMPLATE", VS_STATE_NONE },
		{ 31, "SMALLCAPTIONSIZINGTEMPLATE", VS_STATE_NONE },
		{ 32, "FRAMELEFTSIZINGTEMPLATE", VS_STATE_NONE },
		{ 33, "SMALLFRAMELEFTSIZINGTEMPLATE", VS_STATE_NONE },
		{ 34, "FRAMERIGHTSIZINGTEMPLATE", VS_STATE_NONE },
		{ 35, "SMALLFRAMERIGHTSIZINGTEMPLATE", VS_STATE_NONE },
		{ 36, "FRAMEBOTTOMSIZINGTEMPLATE", VS_STATE_NONE },
		{ 37, "SMALLFRAMEBOTTOMSIZINGTEMPLATE", VS_STATE_NONE },
		{ 38, "FRAME", VS_STATE(STATES_WINDOW_FRAME_GEN) },
	};

	const NameMap PARTS_DWMWINDOW_WIN7[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "FRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 2, "FRAMEBOTTOMSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 3, "RESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "RESTOREBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "MINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "MINBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "CLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "CLOSEBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "CLOSEBUTTON_ONLY", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "CLOSEBUTTON_ONLY", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "CLOSEBUTTONGLOW", VS_STATE_NONE },
		{ 12, "CLOSEBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "CLOSEBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "CLOSEBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "CLOSEBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "MINMAXBUTTONGLOW", VS_STATE_NONE },
		{ 17, "HELPBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "HELPBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "HELPBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "HELPBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "MAXBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MAXBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "MAXBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MAXBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "MINBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "MINBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "MINBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "MINBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "RESTOREBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "RESTOREBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "RESTOREBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 32, "RESTOREBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 33, "FRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 34, "FRAMELEFT_EFFECT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 35, "FRAMELEFTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 36, "FRAMEBOTTOMFADE", VS_STATE_NONE },
		{ 37, "FRAMELEFTFADE", VS_STATE_NONE },
		{ 38, "FRAMERIGHTFADE", VS_STATE_NONE },
		{ 39, "FRAMETOPFADE", VS_STATE_NONE },
		{ 40, "REFLECTIONS", VS_STATE_NONE },
		{ 41, "FRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 42, "FRAMERIGHTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 43, "Part 43", VS_STATE_NONE },
		{ 44, "TOOLFRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TOOLCLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 46, "TOOLCLOSEBUTTON_INACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 47, "TOOLCLOSEBUTTONGLOW", VS_STATE_NONE },
		{ 48, "TOOLCLOSEBUTTON_GLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 49, "TOOLCLOSEBUTTON_GLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 50, "TOOLCLOSEBUTTON_GLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 51, "TOOLCLOSEBUTTON_GLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 52, "TOOLFRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 53, "TOOLFRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 54, "TOOLFRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 55, "TEXTGLOW", VS_STATE_NONE },
		{ 56, "FRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 57, "FRAMETOPSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 58, "FRAMETOP_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 59, "FRAMEBOTTOM_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 60, "Part 60", VS_STATE_NONE },
		{ 61, "Part 61", VS_STATE_NONE },
		{ 62, "FRAMETOP_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 63, "FRAMEBOTTOM_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 64, "TOOLFRAMELEFT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 65, "TOOLFRAMERIGHT_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 66, "TOOLFRAMETOP_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 67, "TOOLFRAMEBOTTOM_PEEK", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 68, "SPINNER", VS_STATE_NONE },
		{ 69, "SNAPINDICATOR", VS_STATE_NONE },
		{ 70, "FRAMETOP_SELECTED", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 71, "FRAMEBOTTOM_SELECTED", VS_STATE(STATES_WINDOW_FRAME_GEN) },
	};

	// Incomplete and maybe incorrect list of parts for Win 8.1
	const NameMap PARTS_DWMWINDOW_WIN81[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "FRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 2, "FRAMEBOTTOMSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 3, "RESTOREBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "RESTOREBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "MINBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "MINBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "CLOSEBUTTON", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "CLOSEBUTTONINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "CLOSEBUTTON_ONLY", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "CLOSEBUTTON_ONLY_INACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "Part 11", VS_STATE_NONE },
		{ 12, "CLOSEBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "CLOSEBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "CLOSEBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "CLOSEBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "HELPBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "HELPBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "HELPBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "HELPBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "MAXBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "MAXBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MAXBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "MAXBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MINBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "MINBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "MINBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "MINBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "RESTOREBUTTON_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "RESTOREBUTTON_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "RESTOREBUTTON_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "RESTOREBUTTON_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 32, "FRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 33, "FRAMELEFTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 34, "FRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 35, "FRAMERIGHTSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 36, "TOOLFRAMEBOTTOM", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 37, "TOOLCLOSE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 38, "TOOLCLOSEINACTIVE", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 39, "TOOLCLOSEGLYPH_96", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 40, "TOOLCLOSEGLYPH_120", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 41, "TOOLCLOSEGLYPH_144", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 42, "TOOLCLOSEGLYPH_192", VS_STATE(STATES_WINDOW_BTN_AND_THUMB) },
		{ 43, "TOOLFRAMELEFT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 44, "TOOLFRAMERIGHT", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TOOLFRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 46, "TEXTGLOW", VS_STATE_NONE },
		{ 47, "FRAMETOP", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 48, "FRAMETOPSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 49, "FRAMETOP_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
		{ 50, "FRAMEBOTTOM_NOSHADOW", VS_STATE(STATES_WINDOW_FRAME_GEN) },
	};

	const NameMap PARTS_EDIT[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "EDITTEXT", VS_STATE(STATES_EDITTEXT) },
		{ 2, "CARET", VS_STATE_NONE },
		{ 3, "BACKGROUND", VS_STATE(STATES_EDITTEXT_BG) },
		{ 4, "PASSWORD", VS_STATE_NONE },
		{ 5, "BACKGROUNDWITHBORDER", VS_STATE(STATES_EDITTEXT_BGWITHBORDER) },
		{ 6, "EDITBORDER_NOSCROLL", VS_STATE(STATES_EDITTEXT_GENERAL) },
		{ 7, "EDITBORDER_HSCROLL", VS_STATE(STATES_EDITTEXT_GENERAL) },
		{ 8, "EDITBORDER_VSCROL", VS_STATE(STATES_EDITTEXT_GENERAL) },
		{ 9, "EDITBORDER_HVSCROLL", VS_STATE(STATES_EDITTEXT_GENERAL) },
	};

	const NameMap PARTS_TASKDIALOG[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "PRIMARYPANEL", VS_STATE_NONE },
		{ 2, "MAININSTRUCTIONPANE", VS_STATE_NONE },
		{ 3, "MAINICON", VS_STATE_NONE },
		{ 4, "CONTENTPANE", VS_STATE_NONE },
		{ 5, "CONTENTICON", VS_STATE_NONE },
		{ 6, "EXPANDEDCONTENT", VS_STATE_NONE },
		{ 7, "COMMANDLINKPANE", VS_STATE_NONE },
		{ 8, "SECONDARYPANEL", VS_STATE_NONE },
		{ 9, "CONTROLPANE", VS_STATE_NONE },
		{ 10, "BUTTONSECTION", VS_STATE_NONE },
		{ 11, "BUTTONWRAPPER", VS_STATE_NONE },
		{ 12, "EXPANDOTEXT", VS_STATE_NONE },
		{ 13, "EXPANDOBUTTON", VS_STATE(STATES_TASKDLG_EXPANDOBUTTON) },
		{ 14, "VERIFICATIONTEXT", VS_STATE_NONE },
		{ 15, "FOOTNOTEPANE", VS_STATE_NONE },
		{ 16, "FOOTNOTEAREA", VS_STATE_NONE },
		{ 17, "FOOTNOTESEPARATOR", VS_STATE_NONE },
		{ 18, "EXPANDEDFOOTERAREA", VS_STATE_NONE },
		{ 19, "PROGRESSBAR", VS_STATE_NONE },
		{ 20, "IMAGEALIGNMENT", VS_STATE_NONE },
		{ 21, "RADIOBUTTONPANE", VS_STATE_NONE },
	};

	const NameMap PARTS_HEADER[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "HEADERITEM", VS_STATE(STATES_HEADER_ITEMSTATES) },
		{ 2, "HEADERITEMLEFT", VS_STATE(STATES_HEADER_LEFT_AND_RIGHT) },
		{ 3, "HEADERITEMRIGHT", VS_STATE(STATES_HEADER_LEFT_AND_RIGHT) },
		{ 4, "HEADERSORTARROW", VS_STATE(STATES_HEADERSORTARROWSTATES) },
		{ 5, "HEADERDROPDOWN", VS_STATE(STATES_HEADERDROPDOWNSTATES) },
		{ 6, "HEADERDROPDOWNFILTER", VS_STATE(STATES_HEADERDROPDOWNFILTERSTATES) },
		{ 7, "HEADEROVERFLOW", VS_STATE(STATES_HEADEROVERFLOWSTATES) },
	};

	const NameMap PARTS_REBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "GRIPPER", VS_STATE_NONE },
		{ 2, "GRIPPERVERT", VS_STATE_NONE },
		{ 3, "BAND", VS_STATE_NONE },
		{ 4, "CHEVRON", VS_STATE(STATES_REBAR_GENERAL) },
		{ 5, "CHEVRONVERT", VS_STATE(STATES_REBAR_GENERAL) },
		{ 6, "BACKGROUND", VS_STATE_NONE },
		{ 7, "SPLITTER", VS_STATE(STATES_REBAR_GENERAL) },
		{ 8, "SPLITTERVERT", VS_STATE(STATES_REBAR_GENERAL) },
	};

	const NameMap PARTS_AEROWIZARD[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "TITLEBAR", VS_STATE_NONE },
		{ 2, "HEADERAREA", VS_STATE_NONE },
		{ 3, "CONTENTAREA", VS_STATE_NONE },
		{ 4, "COMMANDAREA", VS_STATE_NONE },
		{ 5, "BUTTON", VS_STATE_NONE },
	};

	const NameMap PARTS_PROGRESS[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "BAR", VS_STATE_NONE },
		{ 2, "BARVERT", VS_STATE_NONE },
		{ 3, "CHUNK", VS_STATE_NONE },
		{ 4, "CHUNKVERT", VS_STATE_NONE },
		{ 5, "FILL", VS_STATE(STATES_PROGRESS_FILL_GENERAL) },
		{ 6, "FILLVERT", VS_STATE(STATES_PROGRESS_FILL_GENERAL) },
		{ 7, "PULSEOVERLAY", VS_STATE_NONE },
		{ 8, "MOVEOVERLAY", VS_STATE_NONE },
		{ 9, "PULSEOVERLAYVERT", VS_STATE_NONE },
		{ 10, "MOVEOVERLAYVERT", VS_STATE_NONE },
		{ 11, "TRANSPARENTBAR", VS_STATE(STATES_PROGRESS_TRANSPARENT_GENERAL) },
		{ 12, "TRANSPARENTBARVERT", VS_STATE(STATES_PROGRESS_TRANSPARENT_GENERAL) },
	};

	const NameMap PARTS_TRACKBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "TRACK", VS_STATE(STATES_TRACKBAR_GENERAL) },
		{ 2, "TRACKVERT", VS_STATE(STATES_TRACKBAR_GENERAL) },
		{ 3, "THUMB", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 4, "THUMBBOTTOM", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 5, "THUMBTOP", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 6, "THUMBVERT", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 7, "THUMBLEFT", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 8, "THUMBRIGHT", VS_STATE(STATES_TRACKBAR_THUMB_GEN) },
		{ 9, "TICS", VS_STATE(STATES_TRACKBAR_GENERAL) },
		{ 10, "TICSVERT", VS_STATE(STATES_TRACKBAR_GENERAL) },
	};

	const NameMap PARTS_TAB[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "TABITEM", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 2, "TABITEMLEFTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 3, "TABITEMRIGHTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 4, "TABITEMBOTHEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 5, "TOPTABITEM", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 6, "TOPTABITEMLEFTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 7, "TOPTABITEMRIGHTEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 8, "TOPTABITEMBOTHEDGE", VS_STATE(STATES_TABITEM_GENERAL) },
		{ 9, "PANE", VS_STATE_NONE },
		{ 10, "BODY", VS_STATE_NONE },
		{ 11, "AEROWIZARDBODY", VS_STATE_NONE },
	};

	const NameMap PARTS_TOOLTIP[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "STANDARD", VS_STATE(STATES_TOOLTIP_BALLOON_AND_STANDARD) },
		{ 2, "STANDARDTITLE", VS_STATE_NONE },
		{ 3, "BALLOON", VS_STATE(STATES_TOOLTIP_BALLOON_AND_STANDARD) },
		{ 4, "BALLOONTITLE", VS_STATE_NONE },
		{ 5, "CLOSE", VS_STATE(STATES_TOOLTIP_CLOSE) },
		{ 6, "BALLOONSTEM", VS_STATE(STATES_TOOLTIP_BALLOONSTEM) },
		{ 7, "WRENCH", VS_STATE(STATES_TOOLTIP_WRENCH) },
	};

	const NameMap PARTS_TOOLBAR[] =
	{
		{ 0, "Common Properties", VS_STATE(STATES_TOOLBARSTYLE) },
		{ 1, "BUTTON", VS_STATE_NONE },
		{ 2, "DROPDOWNBUTTON", VS_STATE_NONE },
		{ 3, "SPLITBUTTON", VS_STATE_NONE },
		{ 4, "SPLITBUTTONDROPDOWN", VS_STATE_NONE },
		{ 5, "SEPARATOR", VS_STATE_NONE },
		{ 6, "SEPARATORVERT", VS_STATE_NONE },
		{ 7, "DROPDOWNBUTTONGLYPH", VS_STATE_NONE },
	};

	const NameMap PARTS_TASKBAND[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "GROUPCONTENT", VS_STATE_NONE },
		{ 2, "FLASHBUTTON", VS_STATE_NONE },
		{ 3, "FLASHBUTTONGROUPMENU", VS_STATE_NONE },
	};

	const NameMap PARTS_TASKBAND2[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "BARTOP", VS_STATE_NONE },
		{ 2, "BARBOTTOM", VS_STATE_NONE },
		{ 3, "BARRIGHT", VS_STATE_NONE },
		{ 4, "BARLEFT", VS_STATE_NONE },
		{ 5, "TASKITEM", VS_STATE_NONE },
		{ 6, "TASKITEMLEFT", VS_STATE_NONE },
		{ 7, "TASKITEMCENTER", VS_STATE_NONE },
		{ 8, "TASKITEMRIGHT", VS_STATE_NONE },
		{ 9, "PROGRESSITEM", VS_STATE_NONE },
		{ 10, "PROGRESSITEMINDETERMINATE", VS_STATE_NONE },
		{ 11, "PROGRESSITEMERROR", VS_STATE_NONE },
		{ 12, "PROGRESSITEMPAUSED", VS_STATE_NONE },
		{ 13, "TASKITEMGROUP", VS_STATE_NONE },
		{ 14, "TASKITEMGROUPSELECTED", VS_STATE_NONE },
	};

	const NameMap PARTS_TEXTSTYLE[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "MAININSTRUCTION", VS_STATE_NONE },
		{ 2, "INSTRUCTION", VS_STATE_NONE },
		{ 3, "BODYTITLE", VS_STATE_NONE },
		{ 4, "BODYTEXT", VS_STATE_NONE },
		{ 5, "SECONDARYTEXT", VS_STATE_NONE },
		{ 6, "HYPERLINKTEXT", VS_STATE(STATES_TEXTSTYLE_HLINK) },
		{ 7, "EXPANDED", VS_STATE_NONE },
		{ 8, "LABEL", VS_STATE_NONE },
		{ 9, "CONTROLLABEL", VS_STATE(STATES_TEXTSTYLE_CTRLLABEL) },
	};

	const NameMap PARTS_SPIN[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "UP", VS_STATE(STATES_SPIN_GENERAL) },
		{ 2, "DOWN", VS_STATE(STATES_SPIN_GENERAL) },
		{ 3, "UPHORZ", VS_STATE(STATES_SPIN_GENERAL) },
		{ 4, "DOWNHORZ", VS_STATE(STATES_SPIN_GENERAL) },
	};

	const NameMap PARTS_SCROLLBAR[] =
	{
		{ 0, "Common Properties", VS_STATE(STATES_SCROLLBAR_STYLE) },
		{ 1, "ARROWBTN", VS_STATE(STATES_SCROLLBAR_ARROWBTN) },
		{ 2, "THUMBBTNHORZ", VS_STATE_NONE },
		{ 3, "THUMBBTNVERT", VS_STATE_NONE },
		{ 4, "LOWERTRACKHORZ", VS_STATE_NONE },
		{ 5, "UPPERTRACKHORZ", VS_STATE_NONE },
		{ 6, "LOWERTRACKVERT", VS_STATE_NONE },
		{ 7, "UPPERTRACKVERT", VS_STATE_NONE },
		{ 8, "GRIPPERHORZ", VS_STATE_NONE },
		{ 9, "GRIPPERVERT", VS_STATE_NONE },
		{ 10, "SIZEBOX", VS_STATE(STATES_SCROLLBAR_SIZEBOX) },
	};

	const NameMap PARTS_FLYOUT[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "HEADER", VS_STATE(STATES_FLYOUT_HEADER) },
		{ 2, "BODY", VS_STATE(STATES_FLYOUT_BODY) },
		{ 3, "LABEL", VS_STATE(STATES_FLYOUT_LABEL) },
		{ 4, "LINK", VS_STATE(STATES_FLYOUT_LINK) },
		{ 5, "DIVIDER", VS_STATE_NONE },
		{ 6, "WINDOW", VS_STATE_NONE },
		{ 7, "LINKAREA", VS_STATE_NONE },
		{ 8, "LINKHEADER", VS_STATE_NONE },
	};

	const NameMap PARTS_DRAGDROP[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "COPY", VS_STATE(STATES_DND_GENERAL) },
		{ 2, "MOVE", VS_STATE(STATES_DND_GENERAL) },
		{ 3, "UPDATEMETADATA", VS_STATE(STATES_DND_GENERAL) },
		{ 4, "CREATELINK", VS_STATE(STATES_DND_GENERAL) },
		{ 5, "WARNING", VS_STATE(STATES_DND_GENERAL) },
		{ 6, "NONE", VS_STATE(STATES_DND_GENERAL) },
		{ 7, "IMAGEBG", VS_STATE_NONE },
		{ 8, "TEXTBG", VS_STATE_NONE },
	};

	const NameMap PARTS_DATEPICKER[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "DATETEXT", VS_STATE(STATES_DATE_TEXT) },
		{ 2, "DATEBORDER", VS_STATE(STATES_DATE_BORDER) },
		{ 3, "SHOWCALENDARBUTTONRIGHT", VS_STATE(STATES_DATE_CALENDERBUTTONRIGHT) },
	};

	const NameMap PARTS_TASKBAR[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "BACKGROUNDBOTTOM", VS_STATE_NONE },
		{ 2, "BACKGROUNDRIGHT", VS_STATE_NONE },
		{ 3, "BACKGROUNDTOP", VS_STATE_NONE },
		{ 4, "BACKGROUNDLEFT", VS_STATE_NONE },
		{ 5, "SIZINGBARBOTTOM", VS_STATE_NONE },
		{ 6, "SIZINGBARRIGHT", VS_STATE_NONE },
		{ 7, "SIZINGBARTOP", VS_STATE_NONE },
		{ 8, "SIZINGBARLEFT", VS_STATE_NONE },
	};

	const NameMap PARTS_STARTPANEL[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "USERPANE", VS_STATE_NONE },
		{ 2, "MOREPROGRAMS", VS_STATE_NONE },
		{ 3, "MOREPROGRAMSARROW", VS_STATE_NONE },
		{ 4, "PROGRAMLIST", VS_STATE_NONE },
		{ 5, "PROGRAMLISTSEPARATOR", VS_STATE_NONE },
		{ 6, "PLACELIST", VS_STATE_NONE },
		{ 7, "PLACELISTSEPARATOR", VS_STATE_NONE },
		{ 8, "LOGOFF", VS_STATE_NONE },
		{ 9, "LOGOFFBUTTONS", VS_STATE_NONE },
		{ 10, "USERPICTURE", VS_STATE_NONE },
		{ 11, "PREVIEW", VS_STATE_NONE },
		{ 12, "MOREPROGRAMSTAB", VS_STATE_NONE },
		{ 13, "NSCHOST", VS_STATE_NONE },
		{ 14, "SOFTWAREEXPLORER", VS_STATE_NONE },
		{ 15, "OPENBOX", VS_STATE_NONE },
		{ 16, "SEARCHVIEW", VS_STATE_NONE },
		{ 17, "MOREPROGRAMSARROWBACK", VS_STATE_NONE },
		{ 18, "TOPMATCH", VS_STATE_NONE },
		{ 19, "LOGOFFSPLITBUTTONDROPDOWN", VS_STATE_NONE },
	};

	// incomplete list, derived from PARTS_STARTPANEL
	// with a bit of guessing. Works best for Win7.
	const NameMap PARTS_STARTPANELPRIV[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "Part 1", VS_STATE_NONE },
		{ 2, "FRAMELEFT", VS_STATE_NONE },
		{ 3, "FRAMELEFT2", VS_STATE_NONE },
		{ 4, "MOREPROGRAMSARROW", VS_STATE_NONE },
		{ 5, "Part 5", VS_STATE_NONE },
		{ 6, "PROGRAMLIST", VS_STATE_NONE },
		{ 7, "PROGRAMLIST2", VS_STATE_NONE },
		{ 8, "PROGRAMLISTSEPARATOR", VS_STATE_NONE },
		{ 9, "PLACESLIST", VS_STATE_NONE },
		{ 10, "PLACESLIST2", VS_STATE_NONE },
		{ 11, "PLACESLISTSEPARATOR", VS_STATE_NONE },
		{ 12, "Part 12", VS_STATE_NONE },
		{ 13, "Part 13", VS_STATE_NONE },
		{ 14, "FRAMEBOTTOMRIGHT", VS_STATE_NONE },
		{ 15, "FRAMEBOTTOMRIGHT2", VS_STATE_NONE },
		{ 16, "Part 16", VS_STATE_NONE },
		{ 17, "PROGRAMLIST2", VS_STATE_NONE },
		{ 18, "FRAMEBOTTOMLEFT", VS_STATE_NONE },
		{ 19, "FRAMEBOTTOMLEFT2", VS_STATE_NONE },
		{ 20, "SEARCHFRAMETOP", VS_STATE_NONE },
		{ 21, "Part 21", VS_STATE_NONE },
		{ 22, "FRAME_LEFTRIGHT", VS_STATE_NONE },
		{ 23, "LOGOFFSPLITBUTTONDROPDOWNRIGHT", VS_STATE_NONE },
		{ 24, "LOGOFFSPLITBUTTONDROPDOWNRIGHT2", VS_STATE_NONE },
		{ 25, "Part 25", VS_STATE_NONE },
		{ 26, "Part 26", VS_STATE_NONE },
		{ 27, "Part 27", VS_STATE_NONE },
		{ 28, "Part 28", VS_STATE_NONE },
		{ 29, "Part 29", VS_STATE_NONE },
		{ 30, "Part 30", VS_STATE_NONE },
		{ 31, "Part 31", VS_STATE_NONE },
		{ 32, "Part 32", VS_STATE_NONE },
		{ 33, "Part 33", VS_STATE_NONE },
		{ 34, "Part 34", VS_STATE_NONE },
		{ 35, "Part 35", VS_STATE_NONE },
		{ 36, "Part 36", VS_STATE_NONE },
		{ 37, "LOGOFFSPLITBUTTONLEFT", VS_STATE_NONE },
		{ 38, "LOGOFFSPLITBUTTONLEFT2", VS_STATE_NONE },
	};

	const NameMap PARTS_MONTHCAL[] =
	{
		{ 0, "Common Properties", VS_STATE_NONE },
		{ 1, "BACKGROUND", VS_STATE_NONE },
		{ 2, "BORDERS", VS_STATE_NONE },
		{ 3, "GRIDBACKGROUND", VS_STATE_NONE },
		{ 4, "COLHEADERSPLITTER", VS_STATE_NONE },
		{ 5, "GRIDCELLBACKGROUND", VS_STATE_NONE },
		{ 6, "GRIDCELL", VS_STATE_NONE },
		{ 7, "GRIDCELLUPPER", VS_STATE_NONE },
		{ 8, "TRAILINGGRIDCELL", VS_STATE_NONE },
		{ 9, "TRAILINGGRIDCELLUPPER", VS_STATE_NONE },
		{ 10, "NAVNEXT", VS_STATE_NONE },
		{ 11, "NAVPREV", VS_STATE_NONE },
	};
}