#pragma once

#include "VisualStyleStates.h"

#define AL(arr) (sizeof(arr) / sizeof(arr[0]))

namespace msstyle
{
	typedef struct
	{
		int32_t partID;
		const char* partName;
		const StateMap* states;
		const int32_t numStates;
	} NameMap;

	static const NameMap PARTS_BUTTON[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "PUSHBUTTON", STATES_PUSHBUTTON, AL(STATES_PUSHBUTTON) },
		{ 2, "RADIOBUTTON", STATES_RADIOBUTTON, AL(STATES_RADIOBUTTON) },
		{ 3, "CHECKBOX", STATES_CHECKBOX, AL(STATES_CHECKBOX) },
		{ 4, "GROUPBOX", STATES_GROUPBOX, AL(STATES_GROUPBOX) },
		{ 5, "USERBUTTON", 0, 0 },
		{ 6, "COMMANDLINK", STATES_COMMANDLINK, AL(STATES_COMMANDLINK) },
		{ 7, "COMMANDLINKGLYPH", STATES_COMMANDLINKGLYPHS, AL(STATES_COMMANDLINKGLYPHS) }
	};

	static const NameMap PARTS_COMBOBOX[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "DROPDOWNBUTTON", 0, 0 },
		{ 2, "BACKGROUND", 0, 0 },
		{ 3, "TRANSPARENTBACKGROUND", STATES_CB_TRANSPARENTBG, AL(STATES_CB_TRANSPARENTBG) },
		{ 4, "BORDER", STATES_CB_BORDER, AL(STATES_CB_BORDER) },
		{ 5, "READONLY", STATES_CB_READONLY, AL(STATES_CB_READONLY) },
		{ 6, "DROPDOWNBUTTONRIGHT", STATES_CB_DROPDOWNLR, AL(STATES_CB_DROPDOWNLR) },
		{ 7, "DROPDOWNBUTTONLEFT", STATES_CB_DROPDOWNLR, AL(STATES_CB_DROPDOWNLR) },
		{ 8, "CUEBANNER", STATES_CB_CUEBANNER, AL(STATES_CB_CUEBANNER) }
	};

	static const NameMap PARTS_CONTROLPANEL[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "NAVIGATIONPANE", 0, 0 },
		{ 2, "CONTENTPANE", 0, 0 },
		{ 3, "NAVPANELLABEL", 0, 0 },
		{ 4, "CONTENTPANELLABEL", 0, 0 },
		{ 5, "TITLE", 0, 0 },
		{ 6, "BODYTEXT", 0, 0 },
		{ 7, "HELPLINK", STATES_LINK_HELP, AL(STATES_LINK_HELP) },
		{ 8, "TASKLIST", STATES_LINK_TASK, AL(STATES_LINK_TASK) },
		{ 9, "GROUPTEXT", 0, 0 },
		{ 10, "CONTENTLINK", STATES_LINK_CONTENT, AL(STATES_LINK_CONTENT) },
		{ 11, "SECIONTITLELINK", STATES_LINK_SECTIONTITLE, AL(STATES_LINK_SECTIONTITLE) },
		{ 12, "LARGECOMMANDAREA", 0, 0 },
		{ 13, "SMALLCOMMANDAREA", 0, 0 },
		{ 14, "BUTTON", 0, 0 },
		{ 15, "MESSAGETEXT", 0, 0 },
		{ 16, "NAVIGATIONPANELINE", 0, 0 },
		{ 17, "CONTENTPANELINE", 0, 0 },
		{ 18, "BANNERAREA", 0, 0 },
		{ 19, "BODYTITLE", 0, 0 },
	};

	static const NameMap PARTS_EXPLORERBAR[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "HEADERBACKGROUND", 0, 0 },
		{ 2, "HEADERCLOSE", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 3, "HEADERPIN", STATES_EXPLORERBAR_HDRPIN, AL(STATES_EXPLORERBAR_HDRPIN) },
		{ 4, "IEBARMENU", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 5, "NORMALGROUPBACKGROUND", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 6, "NORMALGROUPCOLLAPSE", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 7, "NORMALGROUPEXPAND", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 8, "NORMALGROUPHEAD", 0, 0 },
		{ 9, "SPECIALGROUPBACKGROUND", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 10, "SPECIALGROUPCOLLAPSE", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 11, "SPECIALGROUPEXPAND", STATES_EXPLORERBAR_GENERAL, AL(STATES_EXPLORERBAR_GENERAL) },
		{ 12, "SPECIALGROUPHEAD", 0, 0 },
	};

	static const NameMap PARTS_LISTBOX[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "BORDER_HSCROLL", STATES_LISTBOX_SCROLL, AL(STATES_LISTBOX_ITEMS) },
		{ 2, "BORDER_HVSCROLL", STATES_LISTBOX_SCROLL, AL(STATES_LISTBOX_ITEMS) },
		{ 3, "BORDER_NOSCROLL", STATES_LISTBOX_SCROLL, AL(STATES_LISTBOX_ITEMS) },
		{ 4, "BORDER_VSCROLL", STATES_LISTBOX_SCROLL, AL(STATES_LISTBOX_ITEMS) },
		{ 5, "ITEM", STATES_LISTBOX_ITEMS, AL(STATES_LISTBOX_ITEMS) }
	};

	static const NameMap PARTS_LISTVIEW[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "LISTITEM", STATES_LISTVIEW_ITEMS, AL(STATES_LISTVIEW_ITEMS) },
		{ 2, "LISTGROUP", 0, 0 },
		{ 3, "LISTDETAIL", 0, 0 },
		{ 4, "LISTSORTEDDETAIL", 0, 0 },
		{ 5, "EMPTYTEXT", 0, 0 },
		{ 6, "GROUPHEADER", STATES_LISTVIEW_GROUPHEADER_GENERAL, AL(STATES_LISTVIEW_GROUPHEADER_GENERAL) },
		{ 7, "GROUPHEADERLINE", STATES_LISTVIEW_GROUPHEADER_GENERAL, AL(STATES_LISTVIEW_GROUPHEADER_GENERAL) },
		{ 8, "EXPANDBUTTON", STATES_LISTVIEW_EXPCOLLAPSE, AL(STATES_LISTVIEW_EXPCOLLAPSE) },
		{ 9, "COLLAPSEBUTTON", STATES_LISTVIEW_EXPCOLLAPSE, AL(STATES_LISTVIEW_EXPCOLLAPSE) },
		{ 10, "COLUMNDETAIL", 0, 0 },
	};

	static const NameMap PARTS_MENU[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "MENUITEM", 0, 0 },
		{ 2, "MENUDROPDOWN", 0, 0 },
		{ 3, "MENUBARITEM", STATES_MENU_BARITEM, AL(STATES_MENU_BARITEM) },
		{ 4, "MENUBARDROPDOWN", 0, 0 },
		{ 5, "CHEVRON", 0, 0 },
		{ 6, "SEPARATOR", 0, 0 },
		{ 7, "BARBACKGROUND", 0, 0 },
		{ 8, "BARITEM", STATES_MENU_BARITEM, AL(STATES_MENU_BARITEM) }, // empirically determined
		{ 9, "POPUPBACKGROUND", 0, 0 },
		{ 10, "POPUPBORDERS", 0, 0 },
		{ 11, "POPUPCHECK", STATES_MENU_POPCHECK, AL(STATES_MENU_POPCHECK) },
		{ 12, "POPUPCHECKBACKGROUND", STATES_MENU_POPCHECKBG, AL(STATES_MENU_POPCHECKBG) },
		{ 13, "POPUPGUTTER", 0, 0 },
		{ 14, "POPUPITEM", STATES_MENU_POPITEMS, AL(STATES_MENU_POPITEMS) },
		{ 15, "POPUPSEPARATOR", 0, 0 },
		{ 16, "POPUPSUBMENU", STATES_MENU_SYSTEM_GENERAL, AL(STATES_MENU_SYSTEM_GENERAL) }, // the same as systemXXX states
		{ 17, "SYSTEMCLOSE", STATES_MENU_SYSTEM_GENERAL, AL(STATES_MENU_SYSTEM_GENERAL) },
		{ 18, "SYSTEMMAXIMIZE", STATES_MENU_SYSTEM_GENERAL, AL(STATES_MENU_SYSTEM_GENERAL) },
		{ 19, "SYSTEMMINIMIZE", STATES_MENU_SYSTEM_GENERAL, AL(STATES_MENU_SYSTEM_GENERAL) },
		{ 20, "SYSTEMRESTORE", STATES_MENU_SYSTEM_GENERAL, AL(STATES_MENU_SYSTEM_GENERAL) }
	};

	static const NameMap PARTS_TREEVIEW[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "TREEITEM", STATES_TREEVIEW_ITEM, AL(STATES_TREEVIEW_ITEM) },
		{ 2, "GLYPH", STATES_TREEVIEW_GLYPH, AL(STATES_TREEVIEW_GLYPH) },
		{ 3, "BRANCH", 0, 0 },
		{ 4, "HOTGLYPH", STATES_TREEVIEW_GLYPH, AL(STATES_TREEVIEW_GLYPH) }
	};

	static const NameMap PARTS_WINDOW[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "CAPTION", STATES_WINDOW_CAPTION_GEN, AL(STATES_WINDOW_CAPTION_GEN) },
		{ 2, "SMALLCAPTION", STATES_WINDOW_CAPTION_GEN, AL(STATES_WINDOW_CAPTION_GEN) },
		{ 3, "MINCAPTION", STATES_WINDOW_CAPTION_GEN, AL(STATES_WINDOW_CAPTION_GEN) },
		{ 4, "SMALLMINCAPTION", STATES_WINDOW_CAPTION_GEN, AL(STATES_WINDOW_CAPTION_GEN) },
		{ 5, "MAXCAPTION", STATES_WINDOW_CAPTION_GEN, AL(STATES_WINDOW_CAPTION_GEN) },
		{ 6, "SMALLMAXCAPTION", STATES_WINDOW_CAPTION_GEN, AL(STATES_WINDOW_CAPTION_GEN) },
		{ 7, "FRAMELEFT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 8, "FRAMERIGHT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 9, "FRAMEBOTTOM", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 10, "SMALLFRAMELEFT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 11, "SMALLFRAMERIGHT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 12, "SMALLFRAMEBOTTOM", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 13, "SYSBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "MDISYSBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "MINBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "MDIMINBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "MAXBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "CLOSEBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "SMALLCLOSEBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "MDICLOSEBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "RESTOREBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MDIRESTOREBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "HELPBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MDIHELPBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "HORZSCROLL", 0, 0 },
		{ 26, "HORZTHUMB", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "VERTSCROLL", 0, 0 },
		{ 28, "VERTTHUMB", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "DIALOG", 0, 0 },
		{ 30, "CAPTIONSIZINGTEMPLATE", 0, 0 },
		{ 31, "SMALLCAPTIONSIZINGTEMPLATE", 0, 0 },
		{ 32, "FRAMELEFTSIZINGTEMPLATE", 0, 0 },
		{ 33, "SMALLFRAMELEFTSIZINGTEMPLATE", 0, 0 },
		{ 34, "FRAMERIGHTSIZINGTEMPLATE", 0, 0 },
		{ 35, "SMALLFRAMERIGHTSIZINGTEMPLATE", 0, 0 },
		{ 36, "FRAMEBOTTOMSIZINGTEMPLATE", 0, 0 },
		{ 37, "SMALLFRAMEBOTTOMSIZINGTEMPLATE", 0, 0 },
		{ 38, "FRAME", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) }
	};

	static const NameMap PARTS_DWMWINDOW_WIN7[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "FRAMEBOTTOM", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 2, "FRAMEBOTTOMSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 3, "RESTOREBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "RESTOREBUTTONINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "MINBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "MINBUTTONINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "CLOSEBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "CLOSEBUTTONINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "CLOSEBUTTON_ONLY", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "CLOSEBUTTON_ONLY", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "CLOSEBUTTONGLOW", 0, 0 },
		{ 12, "CLOSEBUTTON_GLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "CLOSEBUTTON_GLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "CLOSEBUTTON_GLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "CLOSEBUTTON_GLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "MINMAXBUTTONGLOW", 0, 0 },
		{ 17, "HELPBUTTON_GLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "HELPBUTTON_GLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "HELPBUTTON_GLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "HELPBUTTON_GLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "MAXBUTTON_GLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MAXBUTTON_GLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "MAXBUTTON_GLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MAXBUTTON_GLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "MINBUTTON_GLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "MINBUTTON_GLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "MINBUTTON_GLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "MINBUTTON_GLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "RESTOREBUTTON_GLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "RESTOREBUTTON_GLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "RESTOREBUTTON_GLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 32, "RESTOREBUTTON_GLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 33, "FRAMELEFT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 34, "FRAMELEFT_EFFECT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 35, "FRAMELEFTSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 36, "FRAMEBOTTOMFADE", 0, 0 },
		{ 37, "FRAMELEFTFADE", 0, 0 },
		{ 38, "FRAMERIGHTFADE", 0, 0 },
		{ 39, "FRAMETOPFADE", 0, 0 },
		{ 40, "REFLECTIONS", 0, 0 },
		{ 41, "FRAMERIGHT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 42, "FRAMERIGHTSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 43, "Part 43", 0, 0 },
		{ 44, "TOOLFRAMEBOTTOM", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TOOLCLOSEBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 46, "TOOLCLOSEBUTTON_INACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 47, "TOOLCLOSEBUTTONGLOW", 0, 0 },
		{ 48, "TOOLCLOSEBUTTON_GLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 49, "TOOLCLOSEBUTTON_GLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 50, "TOOLCLOSEBUTTON_GLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 51, "TOOLCLOSEBUTTON_GLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 52, "TOOLFRAMELEFT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 53, "TOOLFRAMERIGHT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 54, "TOOLFRAMETOP", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 55, "TEXTGLOW", 0, 0 },
		{ 56, "FRAMETOP", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 57, "FRAMETOPSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 58, "FRAMETOP_NOSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 59, "FRAMEBOTTOM_NOSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 60, "Part 60", 0, 0 },
		{ 61, "Part 61", 0, 0 },
		{ 62, "FRAMETOP_PEEK", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 63, "FRAMEBOTTOM_PEEK", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 64, "TOOLFRAMELEFT_PEEK", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 65, "TOOLFRAMERIGHT_PEEK", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 66, "TOOLFRAMETOP_PEEK", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 67, "TOOLFRAMEBOTTOM_PEEK", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 68, "SPINNER", 0, 0 },
		{ 69, "SNAPINDICATOR", 0, 0 },
		{ 70, "FRAMETOP_SELECTED", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 71, "FRAMEBOTTOM_SELECTED", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
	};

	static const NameMap PARTS_DWMWINDOW_WIN81[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "FRAMEBOTTOM", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 2, "FRAMEBOTTOMSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 3, "RESTOREBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 4, "RESTOREBUTTONINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 5, "MINBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 6, "MINBUTTONINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 7, "CLOSEBUTTON", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 8, "CLOSEBUTTONINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 9, "CLOSEBUTTON_ONLY", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 10, "CLOSEBUTTON_ONLY_INACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 11, "Part 11", 0, 0 },
		{ 12, "CLOSEBUTTON_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 13, "CLOSEBUTTON_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 14, "CLOSEBUTTON_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 15, "CLOSEBUTTON_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 16, "HELPBUTTON_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 17, "HELPBUTTON_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 18, "HELPBUTTON_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 19, "HELPBUTTON_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 20, "MAXBUTTON_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 21, "MAXBUTTON_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 22, "MAXBUTTON_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 23, "MAXBUTTON_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 24, "MINBUTTON_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 25, "MINBUTTON_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 26, "MINBUTTON_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 27, "MINBUTTON_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 28, "RESTOREBUTTON_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 29, "RESTOREBUTTON_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 30, "RESTOREBUTTON_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 31, "RESTOREBUTTON_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 32, "FRAMELEFT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 33, "FRAMELEFTSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 34, "FRAMERIGHT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 35, "FRAMERIGHTSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 36, "TOOLFRAMEBOTTOM", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 37, "TOOLCLOSE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 38, "TOOLCLOSEINACTIVE", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 39, "TOOLCLOSEGLYPH_96", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 40, "TOOLCLOSEGLYPH_120", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 41, "TOOLCLOSEGLYPH_144", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 42, "TOOLCLOSEGLYPH_192", STATES_WINDOW_BTN_AND_THUMB, AL(STATES_WINDOW_BTN_AND_THUMB) },
		{ 43, "TOOLFRAMELEFT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 44, "TOOLFRAMERIGHT", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 45, "TOOLFRAMETOP", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 46, "TEXTGLOW", 0, 0 },
		{ 47, "FRAMETOP", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 48, "FRAMETOPSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 49, "FRAMETOP_NOSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
		{ 50, "FRAMEBOTTOM_NOSHADOW", STATES_WINDOW_FRAME_GEN, AL(STATES_WINDOW_FRAME_GEN) },
	};

	static const NameMap PARTS_EDIT[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "EDITTEXT", STATES_EDITTEXT, AL(STATES_EDITTEXT) },
		{ 2, "CARET", 0, 0 },
		{ 3, "BACKGROUND", STATES_EDITTEXT_BG, AL(STATES_EDITTEXT_BG) },
		{ 4, "PASSWORD", 0, 0 },
		{ 5, "BACKGROUNDWITHBORDER", STATES_EDITTEXT_BGWITHBORDER, AL(STATES_EDITTEXT_BGWITHBORDER) },
		{ 6, "EDITBORDER_NOSCROLL", STATES_EDITTEXT_GENERAL, AL(STATES_EDITTEXT_GENERAL) },
		{ 7, "EDITBORDER_HSCROLL", STATES_EDITTEXT_GENERAL, AL(STATES_EDITTEXT_GENERAL) },
		{ 8, "EDITBORDER_VSCROL", STATES_EDITTEXT_GENERAL, AL(STATES_EDITTEXT_GENERAL) },
		{ 9, "EDITBORDER_HVSCROLL", STATES_EDITTEXT_GENERAL, AL(STATES_EDITTEXT_GENERAL) }
	};

	static const NameMap PARTS_TASKDIALOG[] = 
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "PRIMARYPANEL", 0, 0 },
		{ 2, "MAININSTRUCTIONPANE", 0, 0 },
		{ 3, "MAINICON", 0, 0 },
		{ 4, "CONTENTPANE", 0, 0 },
		{ 5, "CONTENTICON", 0, 0 },
		{ 6, "EXPANDEDCONTENT", 0, 0 },
		{ 7, "COMMANDLINKPANE", 0, 0 },
		{ 8, "SECONDARYPANEL", 0, 0 },
		{ 9, "CONTROLPANE", 0, 0 },
		{ 10, "BUTTONSECTION", 0, 0 },
		{ 11, "BUTTONWRAPPER", 0, 0 },
		{ 12, "EXPANDOTEXT", 0, 0 },
		{ 13, "EXPANDOBUTTON", STATES_TASKDLG_EXPANDOBUTTON, AL(STATES_TASKDLG_EXPANDOBUTTON) },
		{ 14, "VERIFICATIONTEXT", 0, 0 },
		{ 15, "FOOTNOTEPANE", 0, 0 },
		{ 16, "FOOTNOTEAREA", 0, 0 },
		{ 17, "FOOTNOTESEPARATOR", 0, 0 },
		{ 18, "EXPANDEDFOOTERAREA", 0, 0 },
		{ 19, "PROGRESSBAR", 0, 0 },
		{ 20, "IMAGEALIGNMENT", 0, 0 },
		{ 21, "RADIOBUTTONPANE", 0, 0 },
	};

	static const NameMap PARTS_HEADER[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "HEADERITEM", STATES_HEADER_ITEMSTATES, AL(STATES_HEADER_ITEMSTATES) },
		{ 2, "HEADERITEMLEFT", STATES_HEADER_LEFT_AND_RIGHT, AL(STATES_HEADER_LEFT_AND_RIGHT) },
		{ 3, "HEADERITEMRIGHT", STATES_HEADER_LEFT_AND_RIGHT, AL(STATES_HEADER_LEFT_AND_RIGHT) },
		{ 4, "HEADERSORTARROW", STATES_HEADERSORTARROWSTATES, AL(STATES_HEADERSORTARROWSTATES) },
		{ 5, "HEADERDROPDOWN", STATES_HEADERDROPDOWNSTATES, AL(STATES_HEADERDROPDOWNSTATES) },
		{ 6, "HEADERDROPDOWNFILTER", STATES_HEADERDROPDOWNFILTERSTATES, AL(STATES_HEADERDROPDOWNFILTERSTATES) },
		{ 7, "HEADEROVERFLOW", STATES_HEADEROVERFLOWSTATES, AL(STATES_HEADEROVERFLOWSTATES) }
	};

	static const NameMap PARTS_REBAR[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "GRIPPER", 0, 0 },
		{ 2, "GRIPPERVERT", 0, 0 },
		{ 3, "BAND", 0, 0 },
		{ 4, "CHEVRON", STATES_REBAR_GENERAL, AL(STATES_REBAR_GENERAL) },
		{ 5, "CHEVRONVERT", STATES_REBAR_GENERAL, AL(STATES_REBAR_GENERAL) },
		{ 6, "BACKGROUND", 0, 0 },
		{ 7, "SPLITTER", STATES_REBAR_GENERAL, AL(STATES_REBAR_GENERAL) },
		{ 8, "SPLITTERVERT", STATES_REBAR_GENERAL, AL(STATES_REBAR_GENERAL) }
	};

	static const NameMap PARTS_AEROWIZARD[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "TITLEBAR", 0, 0 },
		{ 2, "HEADERAREA", 0, 0 },
		{ 3, "CONTENTAREA", 0, 0 },
		{ 4, "COMMANDAREA", 0, 0 },
		{ 5, "BUTTON", 0, 0 },
	};

	static const NameMap PARTS_PROGRESS[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "BAR", 0, 0 },
		{ 2, "BARVERT", 0, 0 },
		{ 3, "CHUNK", 0, 0 },
		{ 4, "CHUNKVERT", 0, 0 },
		{ 5, "FILL", STATES_PROGRESS_FILL_GENERAL, AL(STATES_PROGRESS_FILL_GENERAL) },
		{ 6, "FILLVERT", STATES_PROGRESS_FILL_GENERAL, AL(STATES_PROGRESS_FILL_GENERAL) },
		{ 7, "PULSEOVERLAY", 0, 0 },
		{ 8, "MOVEOVERLAY", 0, 0 },
		{ 9, "PULSEOVERLAYVERT", 0, 0 },
		{ 10, "MOVEOVERLAYVERT", 0, 0 },
		{ 11, "TRANSPARENTBAR", STATES_PROGRESS_TRANSPARENT_GENERAL, AL(STATES_PROGRESS_TRANSPARENT_GENERAL) },
		{ 12, "TRANSPARENTBARVERT", STATES_PROGRESS_TRANSPARENT_GENERAL, AL(STATES_PROGRESS_TRANSPARENT_GENERAL) }
	};

	static const NameMap PARTS_TRACKBAR[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "TRACK", STATES_TRACKBAR_GENERAL, AL(STATES_TRACKBAR_GENERAL) },
		{ 2, "TRACKVERT", STATES_TRACKBAR_GENERAL, AL(STATES_TRACKBAR_GENERAL) },
		{ 3, "THUMB", STATES_TRACKBAR_THUMB_GEN, AL(STATES_TRACKBAR_THUMB_GEN) },
		{ 4, "THUMBBOTTOM", STATES_TRACKBAR_THUMB_GEN, AL(STATES_TRACKBAR_THUMB_GEN) },
		{ 5, "THUMBTOP", STATES_TRACKBAR_THUMB_GEN, AL(STATES_TRACKBAR_THUMB_GEN) },
		{ 6, "THUMBVERT", STATES_TRACKBAR_THUMB_GEN, AL(STATES_TRACKBAR_THUMB_GEN) },
		{ 7, "THUMBLEFT", STATES_TRACKBAR_THUMB_GEN, AL(STATES_TRACKBAR_THUMB_GEN) },
		{ 8, "THUMBRIGHT", STATES_TRACKBAR_THUMB_GEN, AL(STATES_TRACKBAR_THUMB_GEN) },
		{ 9, "TICS", STATES_TRACKBAR_GENERAL, AL(STATES_TRACKBAR_GENERAL) },
		{ 10, "TICSVERT", STATES_TRACKBAR_GENERAL, AL(STATES_TRACKBAR_GENERAL) }
	};

	static const NameMap PARTS_TAB[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "TABITEM", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 2, "TABITEMLEFTEDGE", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 3, "TABITEMRIGHTEDGE", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 4, "TABITEMBOTHEDGE", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 5, "TOPTABITEM", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 6, "TOPTABITEMLEFTEDGE", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 7, "TOPTABITEMRIGHTEDGE", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 8, "TOPTABITEMBOTHEDGE", STATES_TABITEM_GENERAL, AL(STATES_TABITEM_GENERAL) },
		{ 9, "PANE", 0, 0 },
		{ 10, "BODY", 0, 0 },
		{ 11, "AEROWIZARDBODY", 0, 0 },
	};

	static const NameMap PARTS_TOOLTIP[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "STANDARD", STATES_TOOLTIP_BALLOON_AND_STANDARD, AL(STATES_TOOLTIP_BALLOON_AND_STANDARD) },
		{ 2, "STANDARDTITLE", 0, 0 },
		{ 3, "BALLOON", STATES_TOOLTIP_BALLOON_AND_STANDARD, AL(STATES_TOOLTIP_BALLOON_AND_STANDARD) },
		{ 4, "BALLOONTITLE", 0, 0 },
		{ 5, "CLOSE", STATES_TOOLTIP_CLOSE, AL(STATES_TOOLTIP_CLOSE) },
		{ 6, "BALLOONSTEM", STATES_TOOLTIP_BALLOONSTEM, AL(STATES_TOOLTIP_BALLOONSTEM) },
		{ 7, "WRENCH", STATES_TOOLTIP_WRENCH, AL(STATES_TOOLTIP_WRENCH) }
	};

	static const NameMap PARTS_TOOLBAR[] =
	{
		{ 0, "Part 0", STATES_TOOLBARSTYLE, AL(STATES_TOOLBARSTYLE) },
		{ 1, "BUTTON", 0, 0 },
		{ 2, "DROPDOWNBUTTON", 0, 0 },
		{ 3, "SPLITBUTTON", 0, 0 },
		{ 4, "SPLITBUTTONDROPDOWN", 0, 0 },
		{ 5, "SEPARATOR", 0, 0 },
		{ 6, "SEPARATORVERT", 0, 0 },
		{ 7, "DROPDOWNBUTTONGLYPH", 0, 0 },
	};

	static const NameMap PARTS_TASKBAND[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "GROUPCONTENT", 0, 0 },
		{ 2, "FLASHBUTTON", 0, 0 },
		{ 3, "FLASHBUTTONGROUPMENU", 0, 0 },
	};

	static const NameMap PARTS_TASKBAND2[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "BARTOP", 0, 0 },
		{ 2, "BARBOTTOM", 0, 0 },
		{ 3, "BARRIGHT", 0, 0 },
		{ 4, "BARLEFT", 0, 0 },
		{ 5, "TASKITEM", 0, 0 },
		{ 6, "TASKITEMLEFT", 0, 0 },
		{ 7, "TASKITEMCENTER", 0, 0 },
		{ 8, "TASKITEMRIGHT", 0, 0 },
		{ 9, "PROGRESSITEM", 0, 0 },
		{ 10, "PROGRESSITEMINDETERMINATE", 0, 0 },
		{ 11, "PROGRESSITEMERROR", 0, 0 },
		{ 12, "PROGRESSITEMPAUSED", 0, 0 },
		{ 13, "TASKITEMGROUP", 0, 0 },
		{ 14, "TASKITEMGROUPSELECTED", 0, 0 },
	};

	static const NameMap PARTS_TEXTSTYLE[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "MAININSTRUCTION", 0, 0 },
		{ 2, "INSTRUCTION", 0, 0 },
		{ 3, "BODYTITLE", 0, 0 },
		{ 4, "BODYTEXT", 0, 0 },
		{ 5, "SECONDARYTEXT", 0, 0 },
		{ 6, "HYPERLINKTEXT", STATES_TEXTSTYLE_HLINK, AL(STATES_TEXTSTYLE_HLINK) },
		{ 7, "EXPANDED", 0, 0 },
		{ 8, "LABEL", 0, 0 },
		{ 9, "CONTROLLABEL", STATES_TEXTSTYLE_CTRLLABEL, AL(STATES_TEXTSTYLE_CTRLLABEL) }
	};

	static const NameMap PARTS_SPIN[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "UP", STATES_SPIN_GENERAL, AL(STATES_SPIN_GENERAL) },
		{ 2, "DOWN", STATES_SPIN_GENERAL, AL(STATES_SPIN_GENERAL) },
		{ 3, "UPHORZ", STATES_SPIN_GENERAL, AL(STATES_SPIN_GENERAL) },
		{ 4, "DOWNHORZ", STATES_SPIN_GENERAL, AL(STATES_SPIN_GENERAL) }
	};

	static const NameMap PARTS_SCROLLBAR[] =
	{
		{ 0, "Part 0", STATES_SCROLLBAR_STYLE, AL(STATES_SCROLLBAR_STYLE) },
		{ 1, "ARROWBTN", STATES_SCROLLBAR_ARROWBTN, AL(STATES_SCROLLBAR_ARROWBTN) },
		{ 2, "THUMBBTNHORZ", 0, 0 },
		{ 3, "THUMBBTNVERT", 0, 0 },
		{ 4, "LOWERTRACKHORZ", 0, 0 },
		{ 5, "UPPERTRACKHORZ", 0, 0 },
		{ 6, "LOWERTRACKVERT", 0, 0 },
		{ 7, "UPPERTRACKVERT", 0, 0 },
		{ 8, "GRIPPERHORZ", 0, 0 },
		{ 9, "GRIPPERVERT", 0, 0 },
		{ 10, "SIZEBOX", STATES_SCROLLBAR_SIZEBOX, AL(STATES_SCROLLBAR_SIZEBOX) }
	};

	static const NameMap PARTS_FLYOUT[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "HEADER", STATES_FLYOUT_HEADER, AL(STATES_FLYOUT_HEADER) },
		{ 2, "BODY", STATES_FLYOUT_BODY, AL(STATES_FLYOUT_BODY) },
		{ 3, "LABEL", STATES_FLYOUT_LABEL, AL(STATES_FLYOUT_LABEL) },
		{ 4, "LINK", STATES_FLYOUT_LINK, AL(STATES_FLYOUT_LINK) },
		{ 5, "DIVIDER", 0, 0 },
		{ 6, "WINDOW", 0, 0 },
		{ 7, "LINKAREA", 0, 0 },
		{ 8, "LINKHEADER", 0, 0 },
	};

	static const NameMap PARTS_DRAGDROP[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "COPY", STATES_DND_GENERAL, AL(STATES_DND_GENERAL) },
		{ 2, "MOVE", STATES_DND_GENERAL, AL(STATES_DND_GENERAL) },
		{ 3, "UPDATEMETADATA", STATES_DND_GENERAL, AL(STATES_DND_GENERAL) },
		{ 4, "CREATELINK", STATES_DND_GENERAL, AL(STATES_DND_GENERAL) },
		{ 5, "WARNING", STATES_DND_GENERAL, AL(STATES_DND_GENERAL) },
		{ 6, "NONE", STATES_DND_GENERAL, AL(STATES_DND_GENERAL) },
		{ 7, "IMAGEBG", 0, 0 },
		{ 8, "TEXTBG", 0, 0 },
	};

	static const NameMap PARTS_DATEPICKER[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "DATETEXT", STATES_DATE_TEXT, AL(STATES_DATE_TEXT) },
		{ 2, "DATEBORDER", STATES_DATE_BORDER, AL(STATES_DATE_BORDER) },
		{ 3, "SHOWCALENDARBUTTONRIGHT", STATES_DATE_CALENDERBUTTONRIGHT, AL(STATES_DATE_CALENDERBUTTONRIGHT) }
	};

	static const NameMap PARTS_TASKBAR[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "BACKGROUNDBOTTOM", 0, 0 },
		{ 2, "BACKGROUNDRIGHT", 0, 0 },
		{ 3, "BACKGROUNDTOP", 0, 0 },
		{ 4, "BACKGROUNDLEFT", 0, 0 },
		{ 5, "SIZINGBARBOTTOM", 0, 0 },
		{ 6, "SIZINGBARRIGHT", 0, 0 },
		{ 7, "SIZINGBARTOP", 0, 0 },
		{ 8, "SIZINGBARLEFT", 0, 0 },
	};

	static const NameMap PARTS_STARTPANEL[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "USERPANE", 0, 0 },
		{ 2, "MOREPROGRAMS", 0, 0 },
		{ 3, "MOREPROGRAMSARROW", 0, 0 },
		{ 4, "PROGRAMLIST", 0, 0 },
		{ 5, "PROGRAMLISTSEPARATOR", 0, 0 },
		{ 6, "PLACELIST", 0, 0 },
		{ 7, "PLACELISTSEPARATOR", 0, 0 },
		{ 8, "LOGOFF", 0, 0 },
		{ 9, "LOGOFFBUTTONS", 0, 0 },
		{ 10, "USERPICTURE", 0, 0 },
		{ 11, "PREVIEW", 0, 0 },
		{ 12, "MOREPROGRAMSTAB", 0, 0 },
		{ 13, "NSCHOST", 0, 0 },
		{ 14, "SOFTWAREEXPLORER", 0, 0 },
		{ 15, "OPENBOX", 0, 0 },
		{ 16, "SEARCHVIEW", 0, 0 },
		{ 17, "MOREPROGRAMSARROWBACK", 0, 0 },
		{ 18, "TOPMATCH", 0, 0 },
		{ 19, "LOGOFFSPLITBUTTONDROPDOWN", 0, 0 },
	};

	static const NameMap PARTS_MONTHCAL[] =
	{
		{ 0, "Part 0", 0, 0 },
		{ 1, "BACKGROUND", 0, 0 },
		{ 2, "BORDERS", 0, 0 },
		{ 3, "GRIDBACKGROUND", 0, 0 },
		{ 4, "COLHEADERSPLITTER", 0, 0 },
		{ 5, "GRIDCELLBACKGROUND", 0, 0 },
		{ 6, "GRIDCELL", 0, 0 },
		{ 7, "GRIDCELLUPPER", 0, 0 },
		{ 8, "TRAILINGGRIDCELL", 0, 0 },
		{ 9, "TRAILINGGRIDCELLUPPER", 0, 0 },
		{ 10, "NAVNEXT", 0, 0 },
		{ 11, "NAVPREV", 0, 0 },
	};
}